// Differential fuzzing of avro_bridge against Apache avro-cpp, driven by raw
// bytes. Self-contained: this file depends only on the two engines, FuzzTest
// and GoogleTest.
//
// Two properties feed generated bytes to both engines and compare whether each
// accepts. Every divergence they have found has a test named after it below, so
// a reader can see the current state without running anything.
//
// Scope. Each one was reproduced on this host and the tests assert what was
// measured, including the counts that are not yet explained. The properties
// compare *acceptance* only: when both engines accept, the decoded values are
// not compared, so a divergence in a decoded value would not be caught here.
// Object containers, schema resolution and the encode direction are not
// covered at all.

#include <cstdint>
#include <cstdlib>
#include <iterator>
#include <memory>
#include <string>
#include <vector>

#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "avro/Compiler.hh"
#include "avro/Decoder.hh"
#include "avro/Generic.hh"
#include "avro/GenericDatum.hh"
#include "avro/Specific.hh"
#include "avro/Stream.hh"
#include "avro/ValidSchema.hh"
#include "avro_bridge.h"
#include "fuzztest/fuzztest.h"
#include "gtest/gtest.h"

namespace {

using ::security::avro::AvroSchema;

const bool kAllocationCeilingSet = [] {
  security::avro::SetMaxAllocationBytes(64u << 20);
  return true;
}();

// avro-cpp signals errors by throwing while the bridge returns absl::Status,
// so both sides are compared as a Status.
template <typename F>
absl::Status Guarded(F&& body) {
  try {
    body();
    return absl::OkStatus();
  } catch (const std::exception& e) {
    return absl::InternalError(e.what());
  } catch (...) {
    return absl::InternalError("unknown exception");
  }
}

absl::Status ParseWithAvrocpp(const std::string& text,
                              ::avro::ValidSchema* out) {
  return Guarded([&] {
    ::avro::ValidSchema parsed = ::avro::compileJsonSchemaFromMemory(
        reinterpret_cast<const uint8_t*>(text.data()), text.size());
    if (out != nullptr) *out = parsed;
  });
}

absl::Status DecodeWithAvrocpp(const ::avro::ValidSchema& schema,
                               const std::string& bytes,
                               ::avro::GenericDatum* out) {
  return Guarded([&] {
    std::unique_ptr<::avro::InputStream> in = ::avro::memoryInputStream(
        reinterpret_cast<const uint8_t*>(bytes.data()), bytes.size());
    ::avro::DecoderPtr decoder = ::avro::binaryDecoder();
    decoder->init(*in);
    *out = ::avro::GenericDatum(schema);
    ::avro::decode(*decoder, *out);
  });
}

// Avro encodes integers as zigzag varints. Length prefixes, block counts and
// union branch indices all use this, so tests can spell out what a byte string
// means instead of embedding it.
std::string Varint(int64_t value) {
  uint64_t n = (static_cast<uint64_t>(value) << 1) ^
               static_cast<uint64_t>(value >> 63);
  std::string out;
  do {
    uint8_t byte = n & 0x7f;
    n >>= 7;
    if (n != 0) byte |= 0x80;
    out.push_back(static_cast<char>(byte));
  } while (n != 0);
  return out;
}

std::string Hex(const std::string& raw) {
  static const char* kDigits = "0123456789abcdef";
  std::string out;
  out.reserve(raw.size() * 2);
  for (unsigned char c : raw) {
    out += kDigits[c >> 4];
    out += kDigits[c & 0xF];
  }
  return out;
}

// A length prefix far larger than the buffer makes the bridge ask its
// allocator for gigabytes. Rust aborts the process when an allocation fails
// (handle_alloc_error), which no sanitizer setting and no C++ allocator
// replacement can intercept, so such inputs have to be kept away from the
// decoder rather than caught after the fact. They can only end in an error
// from both engines anyway, since the data is not there.
//
// AllocationCeilingChecksCountAgainstAByteLimit records why.
//
// The cost is that scalar values above the limit are never fuzzed.
bool DeclaresLengthBeyondLimit(const std::string& bytes, uint64_t limit) {
  for (size_t start = 0; start < bytes.size(); ++start) {
    uint64_t raw = 0;
    int shift = 0;
    for (size_t i = start; i < bytes.size() && shift < 64; ++i, shift += 7) {
      const uint8_t byte = static_cast<uint8_t>(bytes[i]);
      raw |= static_cast<uint64_t>(byte & 0x7f) << shift;
      if ((byte & 0x80) == 0) {
        const uint64_t magnitude = raw >> 1;
        if (magnitude > limit) return true;
        break;
      }
    }
  }
  return false;
}

// Divergences already triaged. A long run stays quiet on these and stops only
// on something new, so no environment setup is needed to fuzz for hours.
//
// A finding matches when its tag matches and the detail contains `substring`.
// Keep `substring` specific: a broad one hides new findings of the same shape,
// which is the whole failure mode this table exists to avoid. Adding an entry
// means "we have looked at this and written it down", not "make the run green".
//
// Each has a test below named after it, which is what documents the behaviour
// and what fails if it changes.
struct KnownDivergence {
  const char* tag;
  const char* substring;
};

constexpr KnownDivergence kKnownDivergences[] = {
    {"schema-acceptance", "bad node of type union"},
    {"schema-acceptance", "bad node of type enum"},
    {"schema-acceptance", "Invalid namespace"},
    {"bridge-lenient", "EOF reached"},
    {"trailing-bytes", "trailing bytes"},
    {"alloc-ceiling", "Unable to allocate"},
    {"avrocpp-lenient", "Invalid utf-8"},
    {"avrocpp-lenient", "to UUID"},
    {"avrocpp-lenient", "failed to fill whole buffer"},
};

bool IsKnown(const std::string& tag, const std::string& detail) {
  for (const KnownDivergence& known : kKnownDivergences) {
    if (tag == known.tag && detail.find(known.substring) != std::string::npos) {
      return true;
    }
  }
  return false;
}

// AVRO_BYTES_FUZZ_SKIP mutes a finding for one run, for triage. Entries are
// comma-separated and either a bare tag or `tag:substring`.
bool SkippedByEnvironment(const std::string& tag, const std::string& detail) {
  const char* raw = std::getenv("AVRO_BYTES_FUZZ_SKIP");
  if (raw == nullptr) return false;
  std::string list(raw);
  size_t start = 0;
  while (start <= list.size()) {
    const size_t comma = list.find(',', start);
    const std::string entry =
        list.substr(start, comma == std::string::npos ? std::string::npos
                                                     : comma - start);
    if (!entry.empty()) {
      const size_t colon = entry.find(':');
      const std::string want_tag = entry.substr(0, colon);
      if (want_tag == tag &&
          (colon == std::string::npos ||
           detail.find(entry.substr(colon + 1)) != std::string::npos)) {
        return true;
      }
    }
    if (comma == std::string::npos) break;
    start = comma + 1;
  }
  return false;
}

// Fails unless the divergence is already triaged or muted for this run.
void ReportDivergence(const std::string& tag, const std::string& detail) {
  if (IsKnown(tag, detail)) return;
  if (SkippedByEnvironment(tag, detail)) return;
  FAIL() << "[" << tag << "] " << detail;
}

const std::vector<std::string>& SchemaSeeds() {
  static const std::vector<std::string>* seeds = new std::vector<std::string>{
      "[]",
      "[[]]",
      R"(["int"])",
      R"(["int","int"])",
      R"(["null","int"])",
      R"({"type":"enum","name":"E","symbols":[]})",
      R"({"type":"enum","name":"E","symbols":["A","A"]})",
      R"({"type":"record","name":"R","fields":[]})",
      R"({"type":"record","name":"R","fields":[{"name":"a","type":[]}]})",
      R"({"type":"record","name":"R","fields":[{"name":"a","type":"R"}]})",
      R"({"type":"record","name":"R","namespace":"ns","fields":[)"
      R"({"name":"a","type":{"type":"record","name":"R","namespace":"ns",)"
      R"("fields":[]}}]})",
      R"({"type":"array"})",
      R"({"type":"map"})",
      R"({"type":"fixed","name":"F"})",
      R"({"type":"fixed","name":"F","size":-1})",
      R"({"type":"fixed","name":"F","size":99999999999999999999})",
      R"({"type":"fixed","name":"F","namespace":"ns..bad","size":16})",
      R"({"type":"fixed","name":"F","size":12,"logicalType":"duration"})",
      R"({"type":"int","logicalType":"time-millis"})",
      R"({"type":"int","logicalType":"unknown-logical-type"})",
      R"({"type":"bytes","logicalType":"decimal","precision":0,"scale":1})",
      R"({"type":"bytes","logicalType":"decimal","precision":4,"scale":9})",
      R"({"type":"string","logicalType":"uuid"})",
      R"({"type":)",
      R"({"type":"record","name":"R","fields":[)",
      R"({"type":"record","name":"int","fields":[]})",
      R"({"type":"\uD800"})",
      "{}",
      "[",
      "null",
      "0",
      R"("")",
      R"("int")",
      R"("bytes")",
      std::string("\xEF\xBB\xBF") + R"("int")",  // byte-order mark, then a schema
  };
  return *seeds;
}

const std::vector<std::string>& DecodableSchemas() {
  static const std::vector<std::string>* schemas = new std::vector<std::string>{
      R"("null")",
      R"("boolean")",
      R"("int")",
      R"("long")",
      R"("float")",
      R"("double")",
      R"("bytes")",
      R"("string")",
      R"(["int"])",
      R"(["null","int"])",
      R"(["int","string"])",
      R"({"type":"array","items":"int"})",
      R"({"type":"array","items":"string"})",
      R"({"type":"map","values":"int"})",
      R"({"type":"map","values":"bytes"})",
      R"({"type":"enum","name":"E","symbols":["A","B"]})",
      R"({"type":"fixed","name":"F","size":4})",
      R"({"type":"record","name":"R","fields":[{"name":"a","type":"int"}]})",
      R"({"type":"record","name":"R","fields":[)"
      R"({"name":"a","type":"boolean"},{"name":"b","type":"boolean"}]})",
      R"({"type":"record","name":"R","fields":[)"
      R"({"name":"a","type":"string"},{"name":"b","type":["null","int"]}]})",
      R"({"type":"int","logicalType":"date"})",
      R"({"type":"long","logicalType":"timestamp-millis"})",
      R"({"type":"string","logicalType":"uuid"})",
      R"({"type":"bytes","logicalType":"decimal","precision":9,"scale":2})",
  };
  return *schemas;
}

fuzztest::Domain<std::string> AnySchemaText() {
  return fuzztest::OneOf(fuzztest::ElementOf<std::string>(SchemaSeeds()),
                         fuzztest::Arbitrary<std::string>().WithMaxSize(96));
}

void ParsersAgreeOnSchemaAcceptance(const std::string& text) {
  const auto bridge = AvroSchema::Parse(text);
  const absl::Status cpp = ParseWithAvrocpp(text, nullptr);
  if (bridge.ok() == cpp.ok()) return;

  ReportDivergence(
      "schema-acceptance",
      "the two parsers disagree on whether this schema is legal"
      "\n  text:    " + text + "\n  bridge:  " +
          (bridge.ok() ? std::string("accepted")
                       : "rejected: " + std::string(bridge.status().message())) +
          "\n  avrocpp: " +
          (cpp.ok() ? std::string("accepted")
                         : "rejected: " + std::string(cpp.message())));
}
FUZZ_TEST(AvroBytes, ParsersAgreeOnSchemaAcceptance)
    .WithDomains(AnySchemaText());

void DecodersAgreeOnAcceptance(const std::string& schema_text,
                               const std::string& bytes) {
  if (DeclaresLengthBeyondLimit(bytes, 1u << 20)) return;

  auto bridge_schema = AvroSchema::Parse(schema_text);
  ::avro::ValidSchema cpp_schema;
  const absl::Status parsed = ParseWithAvrocpp(schema_text, &cpp_schema);
  if (!bridge_schema.ok() || !parsed.ok()) return;

  const auto bridge = security::avro::DecodeDatum(*bridge_schema, bytes);
  ::avro::GenericDatum datum;
  const absl::Status cpp = DecodeWithAvrocpp(cpp_schema, bytes, &datum);
  if (bridge.ok() == cpp.ok()) return;

  const std::string bridge_error =
      bridge.ok() ? std::string() : std::string(bridge.status().message());
  std::string tag = bridge.ok() ? "bridge-lenient" : "avrocpp-lenient";
  if (!bridge.ok()) {
    if (bridge_error.find("Unable to allocate") != std::string::npos) {
      // avro-cpp has no ceiling, so whether it refuses the same input depends
      // on available memory rather than on the input.
      tag = "alloc-ceiling";
    } else if (bridge_error.find("trailing bytes") != std::string::npos) {
      tag = "trailing-bytes";
    } else if (bridge_error.find("Rust panic caught") != std::string::npos) {
      tag = "rust-panic";
    }
  }
  ReportDivergence(
      tag,
      "the two decoders disagree on whether these bytes are decodable"
      "\n  schema:  " + schema_text +
               "\n  bytes:   " + Hex(bytes) + " (" +
               std::to_string(bytes.size()) + ")\n  bridge:  " +
               (bridge.ok() ? std::string("accepted")
                            : "rejected: " + bridge_error) +
               "\n  avrocpp: " +
               (cpp.ok() ? std::string("accepted")
                         : "rejected: " + std::string(cpp.message())));
}
FUZZ_TEST(AvroBytes, DecodersAgreeOnAcceptance)
    .WithDomains(fuzztest::ElementOf<std::string>(DecodableSchemas()),
                 fuzztest::Arbitrary<std::string>().WithMaxSize(64));

// ---------------------------------------------------------------------------
// One test per divergence in kKnownDivergences, so each is visible on its own
// and fails the moment the behaviour changes. Each spells out what both engines
// do with the same input.
// ---------------------------------------------------------------------------

void ExpectSchemaAcceptance(const std::string& schema, bool bridge_accepts,
                            bool avrocpp_accepts) {
  EXPECT_EQ(AvroSchema::Parse(schema).ok(), bridge_accepts)
      << "the bridge on " << schema;
  EXPECT_EQ(ParseWithAvrocpp(schema, nullptr).ok(), avrocpp_accepts)
      << "avro-cpp on " << schema;
}

void ExpectDecodeAcceptance(const std::string& schema, const std::string& bytes,
                            bool bridge_accepts, bool avrocpp_accepts) {
  auto bridge_schema = AvroSchema::Parse(schema);
  ASSERT_TRUE(bridge_schema.ok()) << bridge_schema.status();
  ::avro::ValidSchema cpp_schema;
  ASSERT_TRUE(ParseWithAvrocpp(schema, &cpp_schema).ok()) << schema;

  const auto bridge = security::avro::DecodeDatum(*bridge_schema, bytes);
  EXPECT_EQ(bridge.ok(), bridge_accepts)
      << "the bridge on " << Hex(bytes) << ": "
      << (bridge.ok() ? "accepted" : std::string(bridge.status().message()));

  ::avro::GenericDatum datum;
  const absl::Status cpp = DecodeWithAvrocpp(cpp_schema, bytes, &datum);
  EXPECT_EQ(cpp.ok(), avrocpp_accepts)
      << "avro-cpp on " << Hex(bytes) << ": "
      << (cpp.ok() ? "accepted" : std::string(cpp.message()));
}

// schema-acceptance / "bad node of type union"
TEST(AvroBytes, EmptyUnionIsAcceptedByTheBridgeOnly) {
  ExpectSchemaAcceptance(R"([])", true, false);
  ExpectSchemaAcceptance(
      R"({"type":"record","name":"R","fields":[{"name":"a","type":[]}]})", true,
      false);

  // And the bridge renders it straight back, so it round-trips a schema
  // avro-cpp cannot read.
  auto parsed = AvroSchema::Parse(R"([])");
  ASSERT_TRUE(parsed.ok());
  auto rendered = parsed->ToJsonString();
  ASSERT_TRUE(rendered.ok());
  EXPECT_EQ(*rendered, R"([])");
}

// schema-acceptance / "bad node of type enum"
TEST(AvroBytes, EmptyEnumIsAcceptedByTheBridgeOnly) {
  ExpectSchemaAcceptance(R"({"type":"enum","name":"E","symbols":[]})", true,
                         false);
}

// schema-acceptance / "Invalid namespace"
TEST(AvroBytes, NamespaceWithAnEmptyComponentIsAcceptedByAvrocppOnly) {
  // The spec requires each namespace component to be a name, so avro-cpp is
  // the lenient one here.
  ExpectSchemaAcceptance(
      R"({"type":"fixed","name":"F","namespace":"ns..bad","size":16})", false,
      true);
}

// bridge-lenient / "EOF reached"
TEST(AvroBytes, EmptyInputIsDecodedByTheBridgeOnly) {
  const std::string record =
      R"({"type":"record","name":"R","fields":[)"
      R"({"name":"a","type":"boolean"},{"name":"b","type":"boolean"}]})";
  ExpectDecodeAcceptance(record, std::string(), true, false);

  // The value it returns does not inhabit its own schema: both boolean fields
  // come back null, from no input at all.
  auto bridge_schema = AvroSchema::Parse(record);
  ASSERT_TRUE(bridge_schema.ok());
  auto decoded = security::avro::DecodeDatum(*bridge_schema, std::string());
  ASSERT_TRUE(decoded.ok());
  auto json = decoded->ToJsonString();
  ASSERT_TRUE(json.ok()) << json.status();
  EXPECT_EQ(*json, R"({"a":null,"b":null})");

  // Type-dependent, which is what makes it easy to miss.
  ExpectDecodeAcceptance(R"("boolean")", std::string(), true, false);
  ExpectDecodeAcceptance(R"(["int"])", std::string(), true, false);
  ExpectDecodeAcceptance(R"("int")", std::string(), false, false);
  ExpectDecodeAcceptance(R"("string")", std::string(), false, false);
  // A null really is zero bytes, so this one is correct on both sides.
  ExpectDecodeAcceptance(R"("null")", std::string(), true, true);
}

// trailing-bytes / "trailing bytes"
TEST(AvroBytes, TrailingBytesAreAcceptedByAvrocppOnly) {
  // One int, then a byte that is not part of it.
  ExpectDecodeAcceptance(R"("int")", Varint(1) + std::string(1, '\x7f'), false,
                         true);
}

// avrocpp-lenient / "Invalid utf-8"
TEST(AvroBytes, NonUtf8StringIsAcceptedByAvrocppOnly) {
  // Length 1, then a lone UTF-8 continuation byte.
  const std::string bytes = Varint(1) + std::string(1, '\x80');
  ExpectDecodeAcceptance(R"("string")", bytes, false, true);
  // The same bytes under a bytes schema are fine on both sides, so the
  // divergence is the string validation and not the payload.
  ExpectDecodeAcceptance(R"("bytes")", bytes, true, true);
}

// avrocpp-lenient / "to UUID"
TEST(AvroBytes, MalformedUuidTextIsAcceptedByAvrocppOnly) {
  const std::string text = "not-a-uuid";
  const std::string bytes =
      Varint(static_cast<int64_t>(text.size())) + text;
  ExpectDecodeAcceptance(R"({"type":"string","logicalType":"uuid"})", bytes,
                         false, true);
  // avro-cpp treats a uuid as an ordinary string, so the plain string schema
  // accepts it on both sides.
  ExpectDecodeAcceptance(R"("string")", bytes, true, true);
}

// avrocpp-lenient / "failed to fill whole buffer"
//
// A 30-item array block followed by a second block header with nothing behind
// it. avro-cpp accepts and hands back 29 items -- fewer than the first block
// declared, with no error -- while the bridge rejects the truncation.
//
// The 29-versus-30 count is not explained; it is recorded as measured. I could
// not reduce this to a smaller input: shorter arrays with the same shape are
// rejected by both engines.
TEST(AvroBytes, TruncatedArrayBlockIsAcceptedByAvrocppOnly) {
  const std::string schema = R"({"type":"array","items":"int"})";
  const std::string bytes = Varint(-30) +            // 30 items, size follows
                            Varint(0) +              // declared block size
                            std::string(30, '\0') +  // 30 items, each 0
                            Varint(-1) +             // a second block header
                            Varint(0);               // its size, then nothing
  ExpectDecodeAcceptance(schema, bytes, false, true);

  ::avro::ValidSchema cpp_schema;
  ASSERT_TRUE(ParseWithAvrocpp(schema, &cpp_schema).ok());
  ::avro::GenericDatum datum;
  ASSERT_TRUE(DecodeWithAvrocpp(cpp_schema, bytes, &datum).ok());
  ASSERT_EQ(datum.type(), ::avro::AVRO_ARRAY);
  EXPECT_EQ(datum.value<::avro::GenericArray>().value().size(), 29u)
      << "avro-cpp returned a different count than when this was recorded";
}

// alloc-ceiling / "Unable to allocate"
TEST(AvroBytes, OversizedLengthStopsAtTheBridgeCeilingOnly) {
  // A bytes field declaring 256 MiB with nothing behind it. The bridge refuses
  // at its ceiling by policy; avro-cpp has no ceiling and only fails because
  // the data is not there, so this input is not comparable in either
  // direction and the fuzz property reports it under its own tag.
  const std::string bytes = Varint(256 << 20);
  ExpectDecodeAcceptance(R"("bytes")", bytes, false, false);

  auto bridge_schema = AvroSchema::Parse(R"("bytes")");
  ASSERT_TRUE(bridge_schema.ok());
  const auto bridge = security::avro::DecodeDatum(*bridge_schema, bytes);
  ASSERT_FALSE(bridge.ok());
  EXPECT_NE(std::string(bridge.status().message()).find("Unable to allocate"),
            std::string::npos)
      << bridge.status().message();
}

// Not an acceptance divergence. The bridge's allocation ceiling compares the
// declared collection *count* against a limit expressed in *bytes*, so a count
// just under the limit passes and the map it then reserves costs about 166
// bytes per entry.
//
// What happens next depends on the host rather than the input: where the
// reservation cannot be satisfied the process aborts, because Rust's
// handle_alloc_error aborts rather than returning an error, and on this host
// overcommit satisfies it and the decode fails cleanly on the missing data.
// The measured abort message was "memory allocation of 5435817992 bytes
// failed". Only the ceiling arithmetic is asserted here, since that is the part
// that does not vary.
//
// DeclaresLengthBeyondLimit keeps such inputs out of the fuzz property, which
// would otherwise abort mid-run on a constrained host.
TEST(AvroBytes, AllocationCeilingChecksCountAgainstAByteLimit) {
  const std::string schema = R"({"type":"map","values":"int"})";
  auto bridge_schema = AvroSchema::Parse(schema);
  ASSERT_TRUE(bridge_schema.ok()) << bridge_schema.status();

  // Above the 64 MiB ceiling: refused, and the number in the message is the
  // entry count rather than the bytes the map would occupy.
  const auto refused =
      security::avro::DecodeDatum(*bridge_schema, Varint(1LL << 30));
  ASSERT_FALSE(refused.ok());
  EXPECT_NE(std::string(refused.status().message())
                .find("Unable to allocate 1073741824 bytes"),
            std::string::npos)
      << refused.status().message();

  // Just under it: the ceiling passes it through, so the reservation that
  // follows is roughly 166 times the number that was checked.
  const auto allowed =
      security::avro::DecodeDatum(*bridge_schema, Varint(32767935));
  ASSERT_FALSE(allowed.ok());
  EXPECT_EQ(std::string(allowed.status().message())
                .find("Unable to allocate"),
            std::string::npos)
      << "the ceiling now covers this count, so the gap is closed: "
      << allowed.status().message();
}

TEST(AvroBytes, KnownDivergenceTableSizeIsPinned) {
  EXPECT_EQ(std::size(kKnownDivergences), 9u)
      << "adding an entry means adding a test named after it above; bump this "
         "count once you have";
}

}  // namespace
