// Differential fuzzing of avro_bridge against Apache avro-cpp, driven by raw
// bytes. Self-contained: this file depends only on the two engines, FuzzTest
// and GoogleTest.
//
// Three properties feed generated bytes to both engines. Two compare whether
// each engine accepts; the third compares what they decoded. Every divergence
// they have found has a test named after it below, so a reader can see the
// current state without running anything.
//
// Scope. Each one was reproduced on this host and the tests assert what was
// measured, including the counts that are not yet explained.
//
// The value comparison is indirect: rather than walk the two decoded values
// field by field, ReencodingAgreesWhenBothDecode has each engine re-encode what
// it decoded and compares the two byte strings. That covers the whole value
// including nesting for very little code, at the price of not saying whether a
// mismatch came from the decoders or the encoders. Maps are excluded from it
// because Avro leaves entry order free and the two engines choose differently;
// see MapsAreExcludedBecauseReencodedEntryOrderIsUnstable.
//
// Object containers and schema resolution are not covered at all.

#include <cctype>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <iterator>
#include <memory>
#include <string>
#include <tuple>
#include <vector>

#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "absl/strings/escaping.h"
#include "avro/Compiler.hh"
#include "avro/Decoder.hh"
#include "avro/Encoder.hh"
#include "avro/Generic.hh"
#include "avro/GenericDatum.hh"
#include "avro/Specific.hh"
#include "avro/Stream.hh"
#include "avro/Types.hh"
#include "avro/ValidSchema.hh"
#include "fuzztest/fuzztest.h"
#include "gtest/gtest.h"

#include "avro_bridge.h"

namespace {

using ::security::avro::AvroSchema;

// The bridge's decoder refuses to reserve more than this in one go.
// AllocationCeilingChecksCountAgainstAByteLimit pins what it actually compares
// against the limit, which is not what the name suggests.
constexpr size_t kAllocationCeilingBytes = 64u << 20;

const bool kAllocationCeilingSet = [] {
  security::avro::SetMaxAllocationBytes(kAllocationCeilingBytes);
  return true;
}();

// EXPERIMENT, do not commit. Both patched apache-avro behaviours on: a
// non-UTF-8 `string` decodes as bytes, and a `uuid` decodes as an ordinary
// string. Together these are what avrocpp already does.
const bool kNonUtf8StringAsBytes = security::avro::SetNonUtf8StringAsBytes(true);
const bool kUuidAsString = security::avro::SetUuidAsString(true);

// Inputs that declare a length above this never reach either decoder. Shared by
// every property that generates bytes, so the properties cannot drift apart:
// see DeclaresLengthBeyondLimit for why the guard has to exist at all.
constexpr uint64_t kMaxDeclaredLengthBytes = 1u << 20;

// avro-cpp signals errors by throwing while the bridge returns absl::Status,
// so both sides are compared as a Status.
template <typename F>
absl::Status Guarded(F&& body) {
  try {
    body();
    return absl::OkStatus();
  } catch (const std::exception& e) {
    return absl::InternalError(e.what());
  } catch (...) {
    return absl::InternalError("unknown exception");
  }
}

absl::Status ParseWithAvrocpp(const std::string& text,
                              ::avro::ValidSchema* out) {
  return Guarded([&] {
    ::avro::ValidSchema parsed = ::avro::compileJsonSchemaFromMemory(
        reinterpret_cast<const uint8_t*>(text.data()), text.size());
    if (out != nullptr) *out = parsed;
  });
}

absl::Status DecodeWithAvrocpp(const ::avro::ValidSchema& schema,
                               const std::string& bytes,
                               ::avro::GenericDatum* out) {
  return Guarded([&] {
    std::unique_ptr<::avro::InputStream> in = ::avro::memoryInputStream(
        reinterpret_cast<const uint8_t*>(bytes.data()), bytes.size());
    ::avro::DecoderPtr decoder = ::avro::binaryDecoder();
    decoder->init(*in);
    *out = ::avro::GenericDatum(schema);
    ::avro::decode(*decoder, *out);
  });
}

absl::Status EncodeWithAvrocpp(const ::avro::ValidSchema& schema,
                               const ::avro::GenericDatum& datum,
                               std::string* out) {
  return Guarded([&] {
    ::avro::OutputStreamPtr stream = ::avro::memoryOutputStream();
    ::avro::EncoderPtr encoder = ::avro::binaryEncoder();
    encoder->init(*stream);
    ::avro::encode(*encoder, datum);
    encoder->flush();
    const std::shared_ptr<std::vector<uint8_t>> bytes =
        ::avro::snapshot(*stream);
    out->assign(bytes->begin(), bytes->end());
  });
}

// Avro encodes integers as zigzag varints. Length prefixes, block counts and
// union branch indices all use this, so tests can spell out what a byte string
// means instead of embedding it.
std::string Varint(int64_t value) {
  uint64_t n = (static_cast<uint64_t>(value) << 1) ^
               static_cast<uint64_t>(value >> 63);
  std::string out;
  do {
    uint8_t byte = n & 0x7f;
    n >>= 7;
    if (n != 0) byte |= 0x80;
    out.push_back(static_cast<char>(byte));
  } while (n != 0);
  return out;
}

// A length prefix far larger than the buffer makes the bridge ask its
// allocator for gigabytes. Rust aborts the process when an allocation fails
// (handle_alloc_error), which no sanitizer setting and no C++ allocator
// replacement can intercept, so such inputs have to be kept away from the
// decoder rather than caught after the fact. They can only end in an error
// from both engines anyway, since the data is not there.
//
// AllocationCeilingChecksCountAgainstAByteLimit records why.
//
// The cost is that scalar values above the limit are never fuzzed.
bool DeclaresLengthBeyondLimit(const std::string& bytes, uint64_t limit) {
  for (size_t start = 0; start < bytes.size(); ++start) {
    uint64_t raw = 0;
    int shift = 0;
    for (size_t i = start; i < bytes.size() && shift < 64; ++i, shift += 7) {
      const uint8_t byte = static_cast<uint8_t>(bytes[i]);
      raw |= static_cast<uint64_t>(byte & 0x7f) << shift;
      if ((byte & 0x80) == 0) {
        const uint64_t magnitude = raw >> 1;
        if (magnitude > limit) return true;
        break;
      }
    }
  }
  return false;
}

// True when two encodings hold the same letters in different case. The bridge
// normalises uuid text to lowercase while avro-cpp keeps what it was given, so
// that shape gets its own tag: a uuid divergence that is not just case folding
// then still surfaces as reencode-differs instead of being swallowed by the
// known-divergence entry.
bool DiffersOnlyByAsciiCase(const std::string& left, const std::string& right) {
  if (left.size() != right.size()) return false;
  bool saw_case_difference = false;
  for (size_t i = 0; i < left.size(); ++i) {
    if (left[i] == right[i]) continue;
    const unsigned char left_char = static_cast<unsigned char>(left[i]);
    const unsigned char right_char = static_cast<unsigned char>(right[i]);
    if (std::tolower(left_char) != std::tolower(right_char)) return false;
    saw_case_difference = true;
  }
  return saw_case_difference;
}

// Divergences already triaged. A long run stays quiet on these and stops only
// on something new, so no environment setup is needed to fuzz for hours.
//
// A finding matches when its tag matches and the detail contains `substring`.
// Keep `substring` specific: a broad one hides new findings of the same shape,
// which is the whole failure mode this table exists to avoid. Adding an entry
// means "we have looked at this and written it down", not "make the run green".
//
// Each has a test below named after it, which is what documents the behaviour
// and what fails if it changes.
struct KnownDivergence {
  const char* tag;
  const char* substring;
};

constexpr KnownDivergence kKnownDivergences[] = {
    {"schema-acceptance", "bad node of type union"},
    {"schema-acceptance", "bad node of type enum"},
    {"schema-acceptance", "Invalid namespace"},
    {"bridge-lenient", "EOF reached"},
    {"trailing-bytes", "trailing bytes"},
    {"alloc-ceiling", "Unable to allocate"},
    {"avrocpp-lenient", "failed to fill whole buffer"},
    {"reencode-failed", "decimal sign extension 0"},
};

bool IsKnown(const std::string& tag, const std::string& detail) {
  for (const KnownDivergence& known : kKnownDivergences) {
    if (tag == known.tag && detail.find(known.substring) != std::string::npos) {
      return true;
    }
  }
  return false;
}

// AVRO_BYTES_FUZZ_SKIP mutes a finding for one run, for triage. Entries are
// comma-separated and either a bare tag or `tag:substring`.
bool SkippedByEnvironment(const std::string& tag, const std::string& detail) {
  const char* raw = std::getenv("AVRO_BYTES_FUZZ_SKIP");
  if (raw == nullptr) return false;
  std::string list(raw);
  size_t start = 0;
  while (start <= list.size()) {
    const size_t comma = list.find(',', start);
    const std::string entry =
        list.substr(start, comma == std::string::npos ? std::string::npos
                                                     : comma - start);
    if (!entry.empty()) {
      const size_t colon = entry.find(':');
      const std::string want_tag = entry.substr(0, colon);
      if (want_tag == tag &&
          (colon == std::string::npos ||
           detail.find(entry.substr(colon + 1)) != std::string::npos)) {
        return true;
      }
    }
    if (comma == std::string::npos) break;
    start = comma + 1;
  }
  return false;
}

// Fails unless the divergence is already triaged or muted for this run.
void ReportDivergence(const std::string& tag, const std::string& detail) {
  if (IsKnown(tag, detail)) return;
  if (SkippedByEnvironment(tag, detail)) return;
  FAIL() << "[" << tag << "] " << detail;
}

const std::vector<std::string>& SchemaSeeds() {
  static const std::vector<std::string>* seeds = new std::vector<std::string>{
      "[]",
      "[[]]",
      R"(["int"])",
      R"(["int","int"])",
      R"(["null","int"])",
      R"({"type":"enum","name":"E","symbols":[]})",
      R"({"type":"enum","name":"E","symbols":["A","A"]})",
      R"({"type":"record","name":"R","fields":[]})",
      R"({"type":"record","name":"R","fields":[{"name":"a","type":[]}]})",
      R"({"type":"record","name":"R","fields":[{"name":"a","type":"R"}]})",
      R"({"type":"record","name":"R","namespace":"ns","fields":[)"
      R"({"name":"a","type":{"type":"record","name":"R","namespace":"ns",)"
      R"("fields":[]}}]})",
      R"({"type":"array"})",
      R"({"type":"map"})",
      R"({"type":"fixed","name":"F"})",
      R"({"type":"fixed","name":"F","size":-1})",
      R"({"type":"fixed","name":"F","size":99999999999999999999})",
      R"({"type":"fixed","name":"F","namespace":"ns..bad","size":16})",
      R"({"type":"fixed","name":"F","size":12,"logicalType":"duration"})",
      R"({"type":"int","logicalType":"time-millis"})",
      R"({"type":"int","logicalType":"unknown-logical-type"})",
      R"({"type":"bytes","logicalType":"decimal","precision":0,"scale":1})",
      R"({"type":"bytes","logicalType":"decimal","precision":4,"scale":9})",
      R"({"type":"string","logicalType":"uuid"})",
      R"({"type":)",
      R"({"type":"record","name":"R","fields":[)",
      R"({"type":"record","name":"int","fields":[]})",
      R"({"type":"\uD800"})",
      "{}",
      "[",
      "null",
      "0",
      R"("")",
      R"("int")",
      R"("bytes")",
      // A byte-order mark, then a schema.
      std::string("\xEF\xBB\xBF") + R"("int")",
  };
  return *seeds;
}

const std::vector<std::string>& DecodableSchemas() {
  static const std::vector<std::string>* schemas = new std::vector<std::string>{
      R"("null")",
      R"("boolean")",
      R"("int")",
      R"("long")",
      R"("float")",
      R"("double")",
      R"("bytes")",
      R"("string")",
      R"(["int"])",
      R"(["null","int"])",
      R"(["int","string"])",
      R"({"type":"array","items":"int"})",
      R"({"type":"array","items":"string"})",
      R"({"type":"map","values":"int"})",
      R"({"type":"map","values":"bytes"})",
      R"({"type":"enum","name":"E","symbols":["A","B"]})",
      R"({"type":"fixed","name":"F","size":4})",
      R"({"type":"record","name":"R","fields":[{"name":"a","type":"int"}]})",
      R"({"type":"record","name":"R","fields":[)"
      R"({"name":"a","type":"boolean"},{"name":"b","type":"boolean"}]})",
      R"({"type":"record","name":"R","fields":[)"
      R"({"name":"a","type":"string"},{"name":"b","type":["null","int"]}]})",
      R"({"type":"int","logicalType":"date"})",
      R"({"type":"long","logicalType":"timestamp-millis"})",
      R"({"type":"string","logicalType":"uuid"})",
      R"({"type":"bytes","logicalType":"decimal","precision":9,"scale":2})",
  };
  return *schemas;
}

// Avro fixes no order for map entries, and the two engines do not agree on one:
// the bridge holds a Rust HashMap, avro-cpp a vector of pairs. Re-encoding a
// map therefore produces two byte strings that differ without either engine
// being wrong, which is a mismatch the round-trip property cannot interpret.
// Compare values under a map by walking the entries instead.
bool MentionsMap(const std::string& schema_text) {
  return schema_text.find(R"("type":"map")") != std::string::npos;
}

const std::vector<std::string>& RoundTripSchemas() {
  static const std::vector<std::string>* schemas = [] {
    auto* filtered = new std::vector<std::string>;
    for (const std::string& schema : DecodableSchemas()) {
      if (!MentionsMap(schema)) filtered->push_back(schema);
    }
    return filtered;
  }();
  return *schemas;
}

// Schema-and-bytes pairs that both engines decode. Used twice: as assertions in
// ReencodingAgreesOnValidEncodings, and as the seed corpus for the round-trip
// property, so a pair cannot rot into an invalid seed without a named test
// failing first.
//
// Seeding is what makes some of these schemas reachable at all. Counting how
// often the property got past its decode guard over 3.5 million generated
// inputs: the uuid schema reached the comparison zero times, because random
// bytes essentially never spell a valid UUID and the bridge validates the
// format. The two multi-field records reached it a few hundred times against
// tens of thousands for the scalars. Mutation starting from a valid encoding
// reaches what mutation starting from noise does not.
const std::vector<std::tuple<std::string, std::string>>& ValidEncodings() {
  static const auto* encodings =
      new std::vector<std::tuple<std::string, std::string>>{
          {R"("null")", ""},
          {R"("boolean")", std::string(1, '\x01')},
          {R"("int")", Varint(1)},
          {R"("long")", Varint(-4096)},
          {R"("float")", std::string("\x00\x00\x80\x3f", 4)},   // 1.0f
          {R"("double")", std::string("\x00\x00\x00\x00\x00\x00\xf0\x3f", 8)},
          {R"("string")", Varint(3) + "abc"},
          {R"("bytes")", Varint(2) + std::string("\x00\xff", 2)},

          // Branch 0 of a single-branch union, then the int 5.
          {R"(["int"])", Varint(0) + Varint(5)},
          // Branch 1 of the union, carrying the int 7.
          {R"(["null","int"])", Varint(1) + Varint(7)},
          // Branch 1 is the string here.
          {R"(["int","string"])", Varint(1) + Varint(2) + "hi"},

          // One block of two items, then the terminating zero-length block.
          {R"({"type":"array","items":"int"})",
           Varint(2) + Varint(10) + Varint(20) + Varint(0)},
          {R"({"type":"array","items":"string"})",
           Varint(1) + Varint(2) + "hi" + Varint(0)},

          {R"({"type":"enum","name":"E","symbols":["A","B"]})", Varint(1)},
          {R"({"type":"fixed","name":"F","size":4})", "wxyz"},

          {R"({"type":"record","name":"R","fields":[)"
           R"({"name":"a","type":"int"}]})",
           Varint(5)},
          {R"({"type":"record","name":"R","fields":[)"
           R"({"name":"a","type":"boolean"},{"name":"b","type":"boolean"}]})",
           std::string("\x01\x00", 2)},
          // A string field, then a union field on its int branch.
          {R"({"type":"record","name":"R","fields":[)"
           R"({"name":"a","type":"string"},)"
           R"({"name":"b","type":["null","int"]}]})",
           Varint(2) + "hi" + Varint(1) + Varint(3)},

          {R"({"type":"int","logicalType":"date"})", Varint(19000)},
          {R"({"type":"long","logicalType":"timestamp-millis"})",
           Varint(1700000000000LL)},
          {R"({"type":"string","logicalType":"uuid"})",
           Varint(36) + "6ba7b810-9dad-11d1-80b4-00c04fd430c8"},
          {R"({"type":"bytes","logicalType":"decimal",)"
           R"("precision":9,"scale":2})",
           Varint(2) + std::string("\x01\x02", 2)},
      };
  return *encodings;
}

fuzztest::Domain<std::string> AnySchemaText() {
  return fuzztest::OneOf(fuzztest::ElementOf<std::string>(SchemaSeeds()),
                         fuzztest::Arbitrary<std::string>().WithMaxSize(96));
}

void ParsersAgreeOnSchemaAcceptance(const std::string& text) {
  const auto bridge = AvroSchema::Parse(text);
  const absl::Status cpp = ParseWithAvrocpp(text, nullptr);
  if (bridge.ok() == cpp.ok()) return;

  const std::string bridge_verdict =
      bridge.ok() ? std::string("accepted")
                  : "rejected: " + std::string(bridge.status().message());
  const std::string cpp_verdict =
      cpp.ok() ? std::string("accepted")
               : "rejected: " + std::string(cpp.message());
  ReportDivergence("schema-acceptance",
                   "the two parsers disagree on whether this schema is legal"
                   "\n  text:    " +
                       text + "\n  bridge:  " + bridge_verdict +
                       "\n  avrocpp: " + cpp_verdict);
}
FUZZ_TEST(AvroBytes, ParsersAgreeOnSchemaAcceptance)
    .WithDomains(AnySchemaText());

void DecodersAgreeOnAcceptance(const std::string& schema_text,
                               const std::string& bytes) {
  if (DeclaresLengthBeyondLimit(bytes, kMaxDeclaredLengthBytes)) return;

  auto bridge_schema = AvroSchema::Parse(schema_text);
  ::avro::ValidSchema cpp_schema;
  const absl::Status parsed = ParseWithAvrocpp(schema_text, &cpp_schema);
  if (!bridge_schema.ok() || !parsed.ok()) return;

  const auto bridge = security::avro::DecodeDatum(*bridge_schema, bytes);
  ::avro::GenericDatum datum;
  const absl::Status cpp = DecodeWithAvrocpp(cpp_schema, bytes, &datum);
  if (bridge.ok() == cpp.ok()) return;

  const std::string bridge_error =
      bridge.ok() ? std::string() : std::string(bridge.status().message());
  std::string tag = bridge.ok() ? "bridge-lenient" : "avrocpp-lenient";
  if (!bridge.ok()) {
    if (bridge_error.find("Unable to allocate") != std::string::npos) {
      // avro-cpp has no ceiling, so whether it refuses the same input depends
      // on available memory rather than on the input.
      tag = "alloc-ceiling";
    } else if (bridge_error.find("trailing bytes") != std::string::npos) {
      tag = "trailing-bytes";
    } else if (bridge_error.find("Rust panic caught") != std::string::npos) {
      tag = "rust-panic";
    }
  }
  ReportDivergence(
      tag,
      "the two decoders disagree on whether these bytes are decodable"
      "\n  schema:  " +
          schema_text + "\n  bytes:   " + absl::BytesToHexString(bytes) + " (" +
          std::to_string(bytes.size()) + ")\n  bridge:  " +
          (bridge.ok() ? std::string("accepted")
                       : "rejected: " + bridge_error) +
          "\n  avrocpp: " +
          (cpp.ok() ? std::string("accepted")
                    : "rejected: " + std::string(cpp.message())));
}
FUZZ_TEST(AvroBytes, DecodersAgreeOnAcceptance)
    .WithDomains(fuzztest::ElementOf<std::string>(DecodableSchemas()),
                 fuzztest::Arbitrary<std::string>().WithMaxSize(64));

// Acceptance alone says nothing about what was decoded, so this property checks
// the values too: when both engines accept the same bytes, each re-encodes what
// it decoded with its own encoder and the two encodings are compared.
//
// What that buys, and what it costs. Comparing encodings covers the whole value
// including nesting without a per-type comparator, but it cannot say which half
// of the circle diverged: a mismatch means the decoders disagreed, or the
// encoders did, or both. Attributing one needs the value walked field by field.
// A mismatch here is therefore a starting point for triage, not a decode bug on
// its own.

void ReencodingAgreesWhenBothDecode(const std::string& schema_text,
                                    const std::string& bytes) {
  if (DeclaresLengthBeyondLimit(bytes, kMaxDeclaredLengthBytes)) return;

  auto bridge_schema = AvroSchema::Parse(schema_text);
  ::avro::ValidSchema cpp_schema;
  const absl::Status parsed = ParseWithAvrocpp(schema_text, &cpp_schema);
  if (!bridge_schema.ok() || !parsed.ok()) return;

  const auto bridge_value = security::avro::DecodeDatum(*bridge_schema, bytes);
  ::avro::GenericDatum cpp_value;
  const absl::Status cpp_decoded =
      DecodeWithAvrocpp(cpp_schema, bytes, &cpp_value);
  // Disagreement on acceptance is DecodersAgreeOnAcceptance's business.
  if (!bridge_value.ok() || !cpp_decoded.ok()) return;

  const auto bridge_reencoded =
      security::avro::EncodeDatum(*bridge_schema, *bridge_value);
  std::string cpp_reencoded;
  const absl::Status cpp_encoded =
      EncodeWithAvrocpp(cpp_schema, cpp_value, &cpp_reencoded);

  if (!bridge_reencoded.ok() || !cpp_encoded.ok()) {
    // One engine decoded a value its own encoder will not accept back.
    ReportDivergence(
        "reencode-failed",
        "both decoded these bytes but re-encoding failed"
        "\n  schema:  " +
            schema_text + "\n  bytes:   " + absl::BytesToHexString(bytes) +
            "\n  bridge:  " +
            (bridge_reencoded.ok()
                 ? std::string("re-encoded")
                 : "failed: " +
                       std::string(bridge_reencoded.status().message())) +
            "\n  avrocpp: " +
            (cpp_encoded.ok()
                 ? std::string("re-encoded")
                 : "failed: " + std::string(cpp_encoded.message())));
    return;
  }

  if (*bridge_reencoded == cpp_reencoded) return;

  ReportDivergence(
      DiffersOnlyByAsciiCase(*bridge_reencoded, cpp_reencoded)
          ? "reencode-case-only"
          : "reencode-differs",
      "both decoded these bytes but re-encoded them differently"
      "\n  schema:  " +
          schema_text + "\n  input:   " + absl::BytesToHexString(bytes) +
          "\n  bridge:  " + absl::BytesToHexString(*bridge_reencoded) +
          "\n  avrocpp: " + absl::BytesToHexString(cpp_reencoded));
}
FUZZ_TEST(AvroBytes, ReencodingAgreesWhenBothDecode)
    .WithDomains(fuzztest::ElementOf<std::string>(RoundTripSchemas()),
                 fuzztest::Arbitrary<std::string>().WithMaxSize(64))
    .WithSeeds(ValidEncodings());

// ---------------------------------------------------------------------------
// One test per divergence in kKnownDivergences, so each is visible on its own
// and fails the moment the behaviour changes. Each spells out what both engines
// do with the same input.
// ---------------------------------------------------------------------------

void ExpectSchemaAcceptance(const std::string& schema, bool bridge_accepts,
                            bool avrocpp_accepts) {
  EXPECT_EQ(AvroSchema::Parse(schema).ok(), bridge_accepts)
      << "the bridge on " << schema;
  EXPECT_EQ(ParseWithAvrocpp(schema, nullptr).ok(), avrocpp_accepts)
      << "avro-cpp on " << schema;
}

void ExpectDecodeAcceptance(const std::string& schema, const std::string& bytes,
                            bool bridge_accepts, bool avrocpp_accepts) {
  auto bridge_schema = AvroSchema::Parse(schema);
  ASSERT_TRUE(bridge_schema.ok()) << bridge_schema.status();
  ::avro::ValidSchema cpp_schema;
  ASSERT_TRUE(ParseWithAvrocpp(schema, &cpp_schema).ok()) << schema;

  const auto bridge = security::avro::DecodeDatum(*bridge_schema, bytes);
  EXPECT_EQ(bridge.ok(), bridge_accepts)
      << "the bridge on " << absl::BytesToHexString(bytes) << ": "
      << (bridge.ok() ? "accepted" : std::string(bridge.status().message()));

  ::avro::GenericDatum datum;
  const absl::Status cpp = DecodeWithAvrocpp(cpp_schema, bytes, &datum);
  EXPECT_EQ(cpp.ok(), avrocpp_accepts)
      << "avro-cpp on " << absl::BytesToHexString(bytes) << ": "
      << (cpp.ok() ? "accepted" : std::string(cpp.message()));
}

// Drives the same circle as ReencodingAgreesWhenBothDecode, but asserts every
// step instead of returning early, so the inputs below are known to reach the
// comparison. The property alone could pass indefinitely while never getting
// past its decode guard, and a passing test that compares nothing is worse than
// no test.
void ExpectReencodingAgrees(const std::string& schema,
                            const std::string& bytes) {
  auto bridge_schema = AvroSchema::Parse(schema);
  ASSERT_TRUE(bridge_schema.ok()) << bridge_schema.status();
  ::avro::ValidSchema cpp_schema;
  ASSERT_TRUE(ParseWithAvrocpp(schema, &cpp_schema).ok()) << schema;

  const auto bridge_value = security::avro::DecodeDatum(*bridge_schema, bytes);
  ASSERT_TRUE(bridge_value.ok())
      << "the bridge on " << absl::BytesToHexString(bytes) << ": "
      << bridge_value.status().message();
  ::avro::GenericDatum cpp_value;
  const absl::Status cpp_decoded =
      DecodeWithAvrocpp(cpp_schema, bytes, &cpp_value);
  ASSERT_TRUE(cpp_decoded.ok())
      << "avro-cpp on " << absl::BytesToHexString(bytes) << ": "
      << cpp_decoded.message();

  const auto bridge_reencoded =
      security::avro::EncodeDatum(*bridge_schema, *bridge_value);
  ASSERT_TRUE(bridge_reencoded.ok()) << bridge_reencoded.status();
  std::string cpp_reencoded;
  const absl::Status cpp_encoded =
      EncodeWithAvrocpp(cpp_schema, cpp_value, &cpp_reencoded);
  ASSERT_TRUE(cpp_encoded.ok()) << cpp_encoded.message();

  // Compared as hex so a mismatch prints legibly.
  EXPECT_EQ(absl::BytesToHexString(*bridge_reencoded),
            absl::BytesToHexString(cpp_reencoded))
      << "schema " << schema << " on input " << absl::BytesToHexString(bytes);
}

TEST(AvroBytes, ReencodingAgreesOnValidEncodings) {
  ASSERT_FALSE(ValidEncodings().empty());
  for (const auto& [schema, bytes] : ValidEncodings()) {
    ExpectReencodingAgrees(schema, bytes);
  }
}

// Why maps sit outside the round-trip property. Feeding these bytes through the
// circle was measured over 15 runs: the two re-encodings differed in 6 of them
// and matched in the other 9, because the bridge writes entries in its HashMap
// iteration order and Rust seeds that per process, while avro-cpp writes them
// in the order they arrived on the wire. Avro fixes no map entry order, so
// neither engine is wrong and a byte comparison would fail intermittently for
// no reason.
//
// What is stable is the content, which is what this test pins, along with the
// exclusion itself.
TEST(AvroBytes, MapsAreExcludedBecauseReencodedEntryOrderIsUnstable) {
  const std::string schema = R"({"type":"map","values":"int"})";
  // Deliberately not in sorted key order, so any reordering is visible.
  const std::string bytes = Varint(2) + Varint(1) + "b" + Varint(20) +
                            Varint(1) + "a" + Varint(10) + Varint(0);

  auto bridge_schema = AvroSchema::Parse(schema);
  ASSERT_TRUE(bridge_schema.ok()) << bridge_schema.status();
  const auto value = security::avro::DecodeDatum(*bridge_schema, bytes);
  ASSERT_TRUE(value.ok()) << value.status();

  const auto keys = value->GetMapKeys();
  ASSERT_TRUE(keys.ok()) << keys.status();
  EXPECT_EQ(*keys, (std::vector<std::string>{"a", "b"}));

  const auto first = value->GetMapValue("a");
  ASSERT_TRUE(first.ok()) << first.status();
  EXPECT_EQ(first->GetInt().value_or(0), 10);
  const auto second = value->GetMapValue("b");
  ASSERT_TRUE(second.ok()) << second.status();
  EXPECT_EQ(second->GetInt().value_or(0), 20);

  // Checked through the parser rather than through MentionsMap, so this is not
  // the filter grading its own work: a map schema written with a space after
  // the colon would slip past the text match and has to be caught here. A map
  // nested inside a record would still get through, which today no seed schema
  // has; the cost if one is added is a noisy report, not a hidden divergence.
  for (const std::string& round_trip_schema : RoundTripSchemas()) {
    auto parsed = AvroSchema::Parse(round_trip_schema);
    ASSERT_TRUE(parsed.ok()) << round_trip_schema;
    EXPECT_FALSE(parsed->IsMap()) << round_trip_schema;
  }
  EXPECT_EQ(RoundTripSchemas().size() + 2, DecodableSchemas().size())
      << "the two map schemas are the only ones the round trip skips";
}

// schema-acceptance / "bad node of type union"
TEST(AvroBytes, EmptyUnionIsAcceptedByTheBridgeOnly) {
  ExpectSchemaAcceptance(R"([])", true, false);
  ExpectSchemaAcceptance(
      R"({"type":"record","name":"R","fields":[{"name":"a","type":[]}]})", true,
      false);

  // And the bridge renders it straight back, so it round-trips a schema
  // avro-cpp cannot read.
  auto parsed = AvroSchema::Parse(R"([])");
  ASSERT_TRUE(parsed.ok());
  auto rendered = parsed->ToJsonString();
  ASSERT_TRUE(rendered.ok());
  EXPECT_EQ(*rendered, R"([])");
}

// schema-acceptance / "bad node of type enum"
TEST(AvroBytes, EmptyEnumIsAcceptedByTheBridgeOnly) {
  ExpectSchemaAcceptance(R"({"type":"enum","name":"E","symbols":[]})", true,
                         false);
}

// schema-acceptance / "Invalid namespace"
TEST(AvroBytes, NamespaceWithAnEmptyComponentIsAcceptedByAvrocppOnly) {
  // The spec requires each namespace component to be a name, so avro-cpp is
  // the lenient one here.
  ExpectSchemaAcceptance(
      R"({"type":"fixed","name":"F","namespace":"ns..bad","size":16})", false,
      true);
}

// bridge-lenient / "EOF reached"
TEST(AvroBytes, EmptyInputIsDecodedByTheBridgeOnly) {
  const std::string record =
      R"({"type":"record","name":"R","fields":[)"
      R"({"name":"a","type":"boolean"},{"name":"b","type":"boolean"}]})";
  ExpectDecodeAcceptance(record, std::string(), true, false);

  // The value it returns does not inhabit its own schema: both boolean fields
  // come back null, from no input at all.
  auto bridge_schema = AvroSchema::Parse(record);
  ASSERT_TRUE(bridge_schema.ok());
  auto decoded = security::avro::DecodeDatum(*bridge_schema, std::string());
  ASSERT_TRUE(decoded.ok());
  auto json = decoded->ToJsonString();
  ASSERT_TRUE(json.ok()) << json.status();
  EXPECT_EQ(*json, R"({"a":null,"b":null})");

  // Type-dependent, which is what makes it easy to miss.
  ExpectDecodeAcceptance(R"("boolean")", std::string(), true, false);
  ExpectDecodeAcceptance(R"(["int"])", std::string(), true, false);
  ExpectDecodeAcceptance(R"("int")", std::string(), false, false);
  ExpectDecodeAcceptance(R"("string")", std::string(), false, false);
  // A null really is zero bytes, so this one is correct on both sides.
  ExpectDecodeAcceptance(R"("null")", std::string(), true, true);
}

// trailing-bytes / "trailing bytes"
TEST(AvroBytes, TrailingBytesAreAcceptedByAvrocppOnly) {
  // One int, then a byte that is not part of it.
  ExpectDecodeAcceptance(R"("int")", Varint(1) + std::string(1, '\x7f'), false,
                         true);
}

// EXPERIMENT. Was avrocpp-lenient / "Invalid utf-8", with the bridge rejecting.
// The non-UTF-8 patch closes it: the bridge accepts and the payload survives as
// bytes, so both engines re-encode to what they were given.
TEST(AvroBytes, NonUtf8StringRoundTripsThroughBothEngines) {
  // Length 1, then a lone UTF-8 continuation byte.
  const std::string bytes = Varint(1) + std::string(1, '\x80');
  ExpectDecodeAcceptance(R"("string")", bytes, true, true);
  ExpectDecodeAcceptance(R"("bytes")", bytes, true, true);

  auto schema = AvroSchema::Parse(R"("string")");
  ASSERT_TRUE(schema.ok()) << schema.status();
  const auto value = security::avro::DecodeDatum(*schema, bytes);
  ASSERT_TRUE(value.ok()) << value.status();
  EXPECT_TRUE(value->IsBytes()) << "type is " << value->TypeName();
  EXPECT_EQ(value->GetBytes().value_or(""), std::string(1, '\x80'));

  // Acceptance says nothing about what was decoded, so drive the whole circle.
  ExpectReencodingAgrees(R"("string")", bytes);
  // Split literals: "\xffb" would lex as one out-of-range hex escape.
  ExpectReencodingAgrees(R"("string")",
                         Varint(4) + std::string("a\xff" "b\x80", 4));
  // A valid UTF-8 string still decodes as a string and is unaffected.
  ExpectReencodingAgrees(R"("string")", Varint(3) + "abc");
}

// EXPERIMENT. Was avrocpp-lenient / "to UUID", with the bridge rejecting text
// that is not a uuid. The uuid-as-string patch closes it, and closes the four
// shapes around it that the acceptance property could never have seen because
// both engines accepted them and only the decoded value differed.
TEST(AvroBytes, UuidIsReadAsAnOrdinaryStringByBothEngines) {
  const std::string uuid_schema = R"({"type":"string","logicalType":"uuid"})";

  // Text that is not a uuid at all: both read it now.
  const std::string text = "not-a-uuid";
  ExpectDecodeAcceptance(uuid_schema,
                         Varint(static_cast<int64_t>(text.size())) + text, true,
                         true);

  // Every spelling below parses as a uuid, so the parsing path rewrote it to
  // canonical hyphenated lowercase and the bytes changed. Read as a string they
  // survive, which is what these assert.
  for (const std::string& body : {
           std::string("6ba7b810-9dad-11d1-80b4-00c04fd430c8"),  // canonical
           std::string("6BA7B810-9DAD-11D1-80B4-00C04FD430C8"),  // upper case
           std::string("urn:uuid:6ba7b810-9dad-11d1-80b4-00c04fd430c8"),
           std::string("{6ba7b810-9dad-11d1-80b4-00c04fd430c8}"),
           std::string("6ba7b8109dad11d180b400c04fd430c8"),  // no hyphens
           std::string("not-a-uuid"),
           std::string(""),
           // Exactly 16 bytes, which the parsing path took as a raw uuid and
           // returned as 36 characters of hex.
           std::string("  St9exception  "),
       }) {
    ExpectReencodingAgrees(uuid_schema,
                           Varint(static_cast<int64_t>(body.size())) + body);
  }

  // Non-UTF-8 under a uuid schema needs both patches: the uuid one to reach the
  // string path at all, the other to tolerate the bytes once there.
  ExpectReencodingAgrees(uuid_schema, Varint(3) + std::string("\xff\xfe\xfd", 3));
}

// avrocpp-lenient / "failed to fill whole buffer"
//
// A 30-item array block followed by a second block header with nothing behind
// it. avro-cpp accepts and hands back 29 items -- fewer than the first block
// declared, with no error -- while the bridge rejects the truncation.
//
// The 29-versus-30 count is not explained; it is recorded as measured. I could
// not reduce this to a smaller input: shorter arrays with the same shape are
// rejected by both engines.
TEST(AvroBytes, TruncatedArrayBlockIsAcceptedByAvrocppOnly) {
  const std::string schema = R"({"type":"array","items":"int"})";
  const std::string bytes = Varint(-30) +            // 30 items, size follows
                            Varint(0) +              // declared block size
                            std::string(30, '\0') +  // 30 items, each 0
                            Varint(-1) +             // a second block header
                            Varint(0);               // its size, then nothing
  ExpectDecodeAcceptance(schema, bytes, false, true);

  ::avro::ValidSchema cpp_schema;
  ASSERT_TRUE(ParseWithAvrocpp(schema, &cpp_schema).ok());
  ::avro::GenericDatum datum;
  ASSERT_TRUE(DecodeWithAvrocpp(cpp_schema, bytes, &datum).ok());
  ASSERT_EQ(datum.type(), ::avro::AVRO_ARRAY);
  EXPECT_EQ(datum.value<::avro::GenericArray>().value().size(), 29u)
      << "avro-cpp returned a different count than when this was recorded";
}

// alloc-ceiling / "Unable to allocate"
TEST(AvroBytes, OversizedLengthStopsAtTheBridgeCeilingOnly) {
  // A bytes field declaring 256 MiB with nothing behind it. The bridge refuses
  // at its ceiling by policy; avro-cpp has no ceiling and only fails because
  // the data is not there, so this input is not comparable in either
  // direction and the fuzz property reports it under its own tag.
  const std::string bytes = Varint(256 << 20);
  ExpectDecodeAcceptance(R"("bytes")", bytes, false, false);

  auto bridge_schema = AvroSchema::Parse(R"("bytes")");
  ASSERT_TRUE(bridge_schema.ok());
  const auto bridge = security::avro::DecodeDatum(*bridge_schema, bytes);
  ASSERT_FALSE(bridge.ok());
  EXPECT_NE(std::string(bridge.status().message()).find("Unable to allocate"),
            std::string::npos)
      << bridge.status().message();
}

// Not an acceptance divergence. The bridge's allocation ceiling compares the
// declared collection *count* against a limit expressed in *bytes*, so a count
// just under the limit passes and the map it then reserves costs about 166
// bytes per entry.
//
// What happens next depends on the host rather than the input: where the
// reservation cannot be satisfied the process aborts, because Rust's
// handle_alloc_error aborts rather than returning an error, and on this host
// overcommit satisfies it and the decode fails cleanly on the missing data.
// The measured abort message was "memory allocation of 5435817992 bytes
// failed". Only the ceiling arithmetic is asserted here, since that is the part
// that does not vary.
//
// DeclaresLengthBeyondLimit keeps such inputs out of the fuzz property, which
// would otherwise abort mid-run on a constrained host.
TEST(AvroBytes, AllocationCeilingChecksCountAgainstAByteLimit) {
  const std::string schema = R"({"type":"map","values":"int"})";
  auto bridge_schema = AvroSchema::Parse(schema);
  ASSERT_TRUE(bridge_schema.ok()) << bridge_schema.status();

  // Above the 64 MiB ceiling: refused, and the number in the message is the
  // entry count rather than the bytes the map would occupy.
  const auto refused =
      security::avro::DecodeDatum(*bridge_schema, Varint(1LL << 30));
  ASSERT_FALSE(refused.ok());
  EXPECT_NE(std::string(refused.status().message())
                .find("Unable to allocate 1073741824 bytes"),
            std::string::npos)
      << refused.status().message();

  // Just under it: the ceiling passes it through, so the reservation that
  // follows is roughly 166 times the number that was checked.
  const auto allowed =
      security::avro::DecodeDatum(*bridge_schema, Varint(32767935));
  ASSERT_FALSE(allowed.ok());
  EXPECT_EQ(std::string(allowed.status().message())
                .find("Unable to allocate"),
            std::string::npos)
      << "the ceiling now covers this count, so the gap is closed: "
      << allowed.status().message();
}

// reencode-failed / "decimal sign extension 0"
//
// Found by ReencodingAgreesWhenBothDecode within five minutes of fuzzing, and
// the first finding the acceptance properties could not have reached: both
// engines accept the input, so they never disagree on acceptance.
//
// A single 0x00 byte under a decimal schema is a length prefix of zero, so the
// unscaled value is an empty byte array. Avro's spec describes that value as a
// two's-complement big-endian integer, which needs at least one byte, so the
// input is arguably malformed and rejecting it would be reasonable. Neither
// decoder does.
//
// What the bridge does instead is worse than either accepting or rejecting: it
// reports success and hands back a value that says it is a decimal but whose
// bytes cannot be read and which its own encoder will not take back, both
// failing with the same message. A caller that decodes this input has no way to
// use or forward the result. avro-cpp decodes it and re-encodes it to the byte
// it came from.
TEST(AvroBytes, EmptyDecimalDecodesToAValueTheBridgeCannotReadOrReencode) {
  const std::string schema =
      R"({"type":"bytes","logicalType":"decimal","precision":9,"scale":2})";
  const std::string bytes = Varint(0);  // a zero-length unscaled value

  auto bridge_schema = AvroSchema::Parse(schema);
  ASSERT_TRUE(bridge_schema.ok()) << bridge_schema.status();
  ::avro::ValidSchema cpp_schema;
  ASSERT_TRUE(ParseWithAvrocpp(schema, &cpp_schema).ok()) << schema;

  const auto bridge_value = security::avro::DecodeDatum(*bridge_schema, bytes);
  ASSERT_TRUE(bridge_value.ok())
      << "the bridge rejected the input outright, which would be a change: "
      << bridge_value.status().message();
  EXPECT_TRUE(bridge_value->IsDecimal());

  // The value claims to be a decimal but will not yield its bytes.
  const auto decimal_bytes = bridge_value->GetDecimalBytes();
  EXPECT_FALSE(decimal_bytes.ok());
  EXPECT_NE(std::string(decimal_bytes.status().message())
                .find("decimal sign extension 0"),
            std::string::npos)
      << decimal_bytes.status().message();

  // And the bridge's own encoder refuses what its decoder produced.
  const auto reencoded =
      security::avro::EncodeDatum(*bridge_schema, *bridge_value);
  EXPECT_FALSE(reencoded.ok());
  EXPECT_NE(std::string(reencoded.status().message())
                .find("decimal sign extension 0"),
            std::string::npos)
      << reencoded.status().message();

  // avro-cpp completes the circle back to the input byte.
  ::avro::GenericDatum cpp_value;
  ASSERT_TRUE(DecodeWithAvrocpp(cpp_schema, bytes, &cpp_value).ok());
  std::string cpp_reencoded;
  ASSERT_TRUE(EncodeWithAvrocpp(cpp_schema, cpp_value, &cpp_reencoded).ok());
  EXPECT_EQ(absl::BytesToHexString(cpp_reencoded),
            absl::BytesToHexString(bytes));
}

// EXPERIMENT. Was reencode-case-only / uuid: the bridge lowercased uuid text
// while avrocpp returned what it was given. With the uuid-as-string patch the
// bridge no longer parses the text, so nothing is folded and the bytes match.
//
// DiffersOnlyByAsciiCase stays: it is what routes any future case-only
// mismatch to its own tag instead of the general reencode-differs one, and the
// unit assertions below keep it honest now that no live input exercises it.
TEST(AvroBytes, UuidTextCaseIsPreservedByBothEngines) {
  const std::string schema = R"({"type":"string","logicalType":"uuid"})";
  const std::string mixed_case = "6BA7B810-9dad-11D1-80b4-00C04FD430C8";
  const std::string bytes = Varint(36) + mixed_case;

  auto bridge_schema = AvroSchema::Parse(schema);
  ASSERT_TRUE(bridge_schema.ok()) << bridge_schema.status();
  const auto bridge_value = security::avro::DecodeDatum(*bridge_schema, bytes);
  ASSERT_TRUE(bridge_value.ok()) << bridge_value.status();
  const auto reencoded =
      security::avro::EncodeDatum(*bridge_schema, *bridge_value);
  ASSERT_TRUE(reencoded.ok()) << reencoded.status();
  EXPECT_EQ(*reencoded, bytes) << "the bridge rewrote the text it was given";

  ExpectReencodingAgrees(schema, bytes);

  EXPECT_TRUE(DiffersOnlyByAsciiCase("AbC", "aBc"));
  EXPECT_FALSE(DiffersOnlyByAsciiCase("abc", "abc"));
  EXPECT_FALSE(DiffersOnlyByAsciiCase("abc", "abd"));
  EXPECT_FALSE(DiffersOnlyByAsciiCase("abc", "abcd"));
}


TEST(AvroBytes, KnownDivergenceTableSizeIsPinned) {
  EXPECT_EQ(std::size(kKnownDivergences), 8u)
      << "adding an entry means adding a test named after it above; bump this "
         "count once you have";
}

}  // namespace
