// Differential fuzzing of avro_bridge against Apache avro-cpp, driven by raw
// bytes. Self-contained: this file depends only on the two engines, FuzzTest
// and GoogleTest.
//
// Three properties feed generated bytes to both engines. Two compare whether
// each engine accepts; the third compares what they decoded. Every divergence
// they have found has a test named after it below, so a reader can see the
// current state without running anything.
//
// Scope. Each one was reproduced on this host and the tests assert what was
// measured, including the counts that are not yet explained.
//
// The value comparison is indirect: rather than walk the two decoded values
// field by field, ReencodingAgreesWhenBothDecode has each engine re-encode what
// it decoded and compares the two byte strings. That covers the whole value
// including nesting for very little code, at the price of not saying whether a
// mismatch came from the decoders or the encoders. Maps are excluded from it
// because Avro leaves entry order free and the two engines choose differently;
// see MapsAreExcludedBecauseReencodedEntryOrderIsUnstable.
//
// Object containers and schema resolution are not covered at all.

#include <cctype>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <iterator>
#include <memory>
#include <string>
#include <tuple>
#include <vector>

#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "absl/strings/escaping.h"
#include "avro/Compiler.hh"
#include "avro/Decoder.hh"
#include "avro/Encoder.hh"
#include "avro/Generic.hh"
#include "avro/GenericDatum.hh"
#include "avro/Specific.hh"
#include "avro/Stream.hh"
#include "avro/Types.hh"
#include "avro/ValidSchema.hh"
#include "fuzztest/fuzztest.h"
#include "gtest/gtest.h"

#include "avro_bridge.h"

namespace {

using ::security::avro::AvroSchema;

// The bridge's decoder refuses to reserve more than this in one go.
// AllocationCeilingChecksCountAgainstAByteLimit pins what it actually compares
// against the limit, which is not what the name suggests.
constexpr size_t kAllocationCeilingBytes = 64u << 20;

const bool kAllocationCeilingSet = [] {
  security::avro::SetMaxAllocationBytes(kAllocationCeilingBytes);
  return true;
}();

// EXPERIMENT, do not commit. Both patched apache-avro behaviours on: a
// non-UTF-8 `string` decodes as bytes, and a `uuid` decodes as an ordinary
// string. Together these are what avrocpp already does.
const bool kNonUtf8StringAsBytes =
    security::avro::SetNonUtf8StringAsBytes(true);
const bool kUuidAsString = security::avro::SetUuidAsString(true);

// Inputs that declare a length above this never reach either decoder. Shared by
// every property that generates bytes, so the properties cannot drift apart:
// see DeclaresLengthBeyondLimit for why the guard has to exist at all.
constexpr uint64_t kMaxDeclaredLengthBytes = 1u << 20;

// avro-cpp signals errors by throwing while the bridge returns absl::Status,
// so both sides are compared as a Status.
template <typename F>
absl::Status Guarded(F&& body) {
  try {
    body();
    return absl::OkStatus();
  } catch (const std::exception& e) {
    return absl::InternalError(e.what());
  } catch (...) {
    return absl::InternalError("unknown exception");
  }
}

absl::Status ParseWithAvrocpp(const std::string& text,
                              ::avro::ValidSchema* out) {
  return Guarded([&] {
    ::avro::ValidSchema parsed = ::avro::compileJsonSchemaFromMemory(
        reinterpret_cast<const uint8_t*>(text.data()), text.size());
    if (out != nullptr) *out = parsed;
  });
}

absl::Status DecodeWithAvrocpp(const ::avro::ValidSchema& schema,
                               const std::string& bytes,
                               ::avro::GenericDatum* out) {
  return Guarded([&] {
    std::unique_ptr<::avro::InputStream> in = ::avro::memoryInputStream(
        reinterpret_cast<const uint8_t*>(bytes.data()), bytes.size());
    ::avro::DecoderPtr decoder = ::avro::binaryDecoder();
    decoder->init(*in);
    *out = ::avro::GenericDatum(schema);
    ::avro::decode(*decoder, *out);
  });
}

absl::Status EncodeWithAvrocpp(const ::avro::ValidSchema& schema,
                               const ::avro::GenericDatum& datum,
                               std::string* out) {
  return Guarded([&] {
    ::avro::OutputStreamPtr stream = ::avro::memoryOutputStream();
    ::avro::EncoderPtr encoder = ::avro::binaryEncoder();
    encoder->init(*stream);
    ::avro::encode(*encoder, datum);
    encoder->flush();
    const std::shared_ptr<std::vector<uint8_t>> bytes =
        ::avro::snapshot(*stream);
    out->assign(bytes->begin(), bytes->end());
  });
}

// Avro encodes integers as zigzag varints. Length prefixes, block counts and
// union branch indices all use this, so tests can spell out what a byte string
// means instead of embedding it.
std::string Varint(int64_t value) {
  uint64_t n = (static_cast<uint64_t>(value) << 1) ^
               static_cast<uint64_t>(value >> 63);
  std::string out;
  do {
    uint8_t byte = n & 0x7f;
    n >>= 7;
    if (n != 0) byte |= 0x80;
    out.push_back(static_cast<char>(byte));
  } while (n != 0);
  return out;
}

// For byte strings that carry no structure worth spelling out, such as a fuzzer
// counterexample kept verbatim.
std::string FromHex(absl::string_view hex) {
  std::string out;
  out.reserve(hex.size() / 2);
  for (size_t i = 0; i + 1 < hex.size(); i += 2) {
    out.push_back(static_cast<char>(
        std::stoi(std::string(hex.substr(i, 2)), nullptr, 16)));
  }
  return out;
}

// A length prefix far larger than the buffer makes the bridge ask its
// allocator for gigabytes. Rust aborts the process when an allocation fails
// (handle_alloc_error), which no sanitizer setting and no C++ allocator
// replacement can intercept, so such inputs have to be kept away from the
// decoder rather than caught after the fact. They can only end in an error
// from both engines anyway, since the data is not there.
//
// AllocationCeilingChecksCountAgainstAByteLimit records why.
//
// The cost is that scalar values above the limit are never fuzzed.
bool DeclaresLengthBeyondLimit(const std::string& bytes, uint64_t limit) {
  for (size_t start = 0; start < bytes.size(); ++start) {
    uint64_t raw = 0;
    int shift = 0;
    for (size_t i = start; i < bytes.size() && shift < 64; ++i, shift += 7) {
      const uint8_t byte = static_cast<uint8_t>(bytes[i]);
      raw |= static_cast<uint64_t>(byte & 0x7f) << shift;
      if ((byte & 0x80) == 0) {
        const uint64_t magnitude = raw >> 1;
        if (magnitude > limit) return true;
        break;
      }
    }
  }
  return false;
}

// Avro says nothing about how to recover from a malformed array block header,
// and the two engines each picked something. A negative item count whose byte
// size is also negative, a count that overflows the long it is read into, a
// count larger than any vector can hold, a block that ends early: these are one
// root cause wearing four messages, so they get one tag rather than an entry
// per spelling. ArrayBlockHeaderRecoveryDiverges holds the measured evidence.
//
// The tag is assigned by schema shape, so it covers any divergence under an
// array, not only a framing one. That is the cost of consolidating: there is
// nothing in a decoder's error message that separates a bad header from a bad
// item. It is applied only in place of the generic lenient tags, so
// alloc-ceiling, trailing-bytes and rust-panic still win under an
// array.
bool IsArraySchema(const std::string& schema_text) {
  auto parsed = AvroSchema::Parse(schema_text);
  return parsed.ok() && parsed->IsArray();
}

// avrocpp stops once it has a complete JSON value and never looks at what
// follows, so a schema with anything after it still parses while the bridge
// refuses it. The bridge reports that three different ways depending on where
// the trailing bytes fail first, which is why this is classified by shape
// rather than by message: a proper prefix of the text parses on its own.
//
// The scan is linear in the length of the text and runs only once a divergence
// has already been found, never on the hot path.
bool ParsesAsSchemaPrefix(const std::string& text) {
  for (size_t len = text.size(); len-- > 1;) {
    if (AvroSchema::Parse(text.substr(0, len)).ok()) return true;
  }
  return false;
}

// Divergences already triaged. A long run stays quiet on these and stops only
// on something new, so no environment setup is needed to fuzz for hours.
//
// A finding matches when its tag matches and the detail contains `substring`.
// Keep `substring` specific: a broad one hides new findings of the same shape,
// which is the whole failure mode this table exists to avoid. Adding an entry
// means "we have looked at this and written it down", not "make the run green".
//
// Each has a test below named after it, which is what documents the behaviour
// and what fails if it changes.
struct KnownDivergence {
  const char* tag;
  const char* substring;
};

constexpr KnownDivergence kKnownDivergences[] = {
    {"schema-acceptance", "Invalid namespace"},
    {"trailing-bytes", "trailing bytes"},
    {"alloc-ceiling", "Unable to allocate"},
    // One root cause, four messages: see IsArraySchema above.
    {"array-block-framing", R"("type":"array")"},
    // Likewise one root cause, three messages: see ParsesAsSchemaPrefix.
    {"schema-trailing-bytes", "disagree on whether this schema is legal"},
    {"avrocpp-lenient", "Invalid utf-8 string"},
    {"reencode-failed", "decimal sign extension 0"},
    {"json-whitespace-leniency", "disagree on whether this schema is legal"},
};

bool IsKnown(const std::string& tag, const std::string& detail) {
  for (const KnownDivergence& known : kKnownDivergences) {
    if (tag == known.tag && detail.find(known.substring) != std::string::npos) {
      return true;
    }
  }
  return false;
}

// AVRO_BYTES_FUZZ_SKIP mutes a finding for one run, for triage. Entries are
// comma-separated and either a bare tag or `tag:substring`.
bool SkippedByEnvironment(const std::string& tag, const std::string& detail) {
  const char* raw = std::getenv("AVRO_BYTES_FUZZ_SKIP");
  if (raw == nullptr) return false;
  std::string list(raw);
  size_t start = 0;
  while (start <= list.size()) {
    const size_t comma = list.find(',', start);
    const std::string entry =
        list.substr(start, comma == std::string::npos ? std::string::npos
                                                     : comma - start);
    if (!entry.empty()) {
      const size_t colon = entry.find(':');
      const std::string want_tag = entry.substr(0, colon);
      if (want_tag == tag &&
          (colon == std::string::npos ||
           detail.find(entry.substr(colon + 1)) != std::string::npos)) {
        return true;
      }
    }
    if (comma == std::string::npos) break;
    start = comma + 1;
  }
  return false;
}

// Fails unless the divergence is already triaged or muted for this run.
void ReportDivergence(const std::string& tag, const std::string& detail) {
  if (IsKnown(tag, detail)) return;
  if (SkippedByEnvironment(tag, detail)) return;
  FAIL() << "[" << tag << "] " << detail;
}

const std::vector<std::string>& SchemaSeeds() {
  static const std::vector<std::string>* seeds = new std::vector<std::string>{
      "[]",
      "[[]]",
      R"(["int"])",
      R"(["int","int"])",
      R"(["null","int"])",
      R"({"type":"enum","name":"E","symbols":[]})",
      R"({"type":"enum","name":"E","symbols":["A","A"]})",
      R"({"type":"record","name":"R","fields":[]})",
      R"({"type":"record","name":"R","fields":[{"name":"a","type":[]}]})",
      R"({"type":"record","name":"R","fields":[{"name":"a","type":"R"}]})",
      R"({"type":"record","name":"R","namespace":"ns","fields":[)"
      R"({"name":"a","type":{"type":"record","name":"R","namespace":"ns",)"
      R"("fields":[]}}]})",
      R"({"type":"array"})",
      R"({"type":"map"})",
      R"({"type":"fixed","name":"F"})",
      R"({"type":"fixed","name":"F","size":-1})",
      R"({"type":"fixed","name":"F","size":99999999999999999999})",
      R"({"type":"fixed","name":"F","namespace":"ns..bad","size":16})",
      R"({"type":"fixed","name":"F","size":12,"logicalType":"duration"})",
      R"({"type":"int","logicalType":"time-millis"})",
      R"({"type":"int","logicalType":"unknown-logical-type"})",
      R"({"type":"bytes","logicalType":"decimal","precision":0,"scale":1})",
      R"({"type":"bytes","logicalType":"decimal","precision":4,"scale":9})",
      R"({"type":"string","logicalType":"uuid"})",
      R"({"type":)",
      R"({"type":"record","name":"R","fields":[)",
      R"({"type":"record","name":"int","fields":[]})",
      R"({"type":"\uD800"})",
      "{}",
      "[",
      "null",
      "0",
      R"("")",
      R"("int")",
      R"("bytes")",
      // A byte-order mark, then a schema.
      std::string("\xEF\xBB\xBF") + R"("int")",
  };
  return *seeds;
}

const std::vector<std::string>& DecodableSchemas() {
  static const std::vector<std::string>* schemas = new std::vector<std::string>{
      R"("null")",
      R"("boolean")",
      R"("int")",
      R"("long")",
      R"("float")",
      R"("double")",
      R"("bytes")",
      R"("string")",
      R"(["int"])",
      R"(["null","int"])",
      R"(["int","string"])",
      R"({"type":"array","items":"int"})",
      R"({"type":"array","items":"string"})",
      R"({"type":"map","values":"int"})",
      R"({"type":"map","values":"bytes"})",
      R"({"type":"enum","name":"E","symbols":["A","B"]})",
      R"({"type":"fixed","name":"F","size":4})",
      R"({"type":"record","name":"R","fields":[{"name":"a","type":"int"}]})",
      R"({"type":"record","name":"R","fields":[)"
      R"({"name":"a","type":"boolean"},{"name":"b","type":"boolean"}]})",
      R"({"type":"record","name":"R","fields":[)"
      R"({"name":"a","type":"string"},{"name":"b","type":["null","int"]}]})",
      R"({"type":"int","logicalType":"date"})",
      R"({"type":"long","logicalType":"timestamp-millis"})",
      R"({"type":"string","logicalType":"uuid"})",
      R"({"type":"bytes","logicalType":"decimal","precision":9,"scale":2})",
  };
  return *schemas;
}

// Avro fixes no order for map entries, and the two engines do not agree on one:
// the bridge holds a Rust HashMap, avro-cpp a vector of pairs. Re-encoding a
// map therefore produces two byte strings that differ without either engine
// being wrong, which is a mismatch the round-trip property cannot interpret.
// Compare values under a map by walking the entries instead.
bool MentionsMap(const std::string& schema_text) {
  return schema_text.find(R"("type":"map")") != std::string::npos;
}

const std::vector<std::string>& RoundTripSchemas() {
  static const std::vector<std::string>* schemas = [] {
    auto* filtered = new std::vector<std::string>;
    for (const std::string& schema : DecodableSchemas()) {
      if (!MentionsMap(schema)) filtered->push_back(schema);
    }
    return filtered;
  }();
  return *schemas;
}

// Schema-and-bytes pairs that both engines decode. Used twice: as assertions in
// ReencodingAgreesOnValidEncodings, and as the seed corpus for the round-trip
// property, so a pair cannot rot into an invalid seed without a named test
// failing first.
//
// Seeding is what makes some of these schemas reachable at all. Counting how
// often the property got past its decode guard over 3.5 million generated
// inputs: the uuid schema reached the comparison zero times, because random
// bytes essentially never spell a valid UUID and the bridge validates the
// format. The two multi-field records reached it a few hundred times against
// tens of thousands for the scalars. Mutation starting from a valid encoding
// reaches what mutation starting from noise does not.
const std::vector<std::tuple<std::string, std::string>>& ValidEncodings() {
  static const auto* encodings =
      new std::vector<std::tuple<std::string, std::string>>{
          {R"("null")", ""},
          {R"("boolean")", std::string(1, '\x01')},
          {R"("int")", Varint(1)},
          {R"("long")", Varint(-4096)},
          {R"("float")", std::string("\x00\x00\x80\x3f", 4)},   // 1.0f
          {R"("double")", std::string("\x00\x00\x00\x00\x00\x00\xf0\x3f", 8)},
          {R"("string")", Varint(3) + "abc"},
          {R"("bytes")", Varint(2) + std::string("\x00\xff", 2)},

          // Branch 0 of a single-branch union, then the int 5.
          {R"(["int"])", Varint(0) + Varint(5)},
          // Branch 1 of the union, carrying the int 7.
          {R"(["null","int"])", Varint(1) + Varint(7)},
          // Branch 1 is the string here.
          {R"(["int","string"])", Varint(1) + Varint(2) + "hi"},

          // One block of two items, then the terminating zero-length block.
          {R"({"type":"array","items":"int"})",
           Varint(2) + Varint(10) + Varint(20) + Varint(0)},
          {R"({"type":"array","items":"string"})",
           Varint(1) + Varint(2) + "hi" + Varint(0)},

          {R"({"type":"enum","name":"E","symbols":["A","B"]})", Varint(1)},
          {R"({"type":"fixed","name":"F","size":4})", "wxyz"},

          {R"({"type":"record","name":"R","fields":[)"
           R"({"name":"a","type":"int"}]})",
           Varint(5)},
          {R"({"type":"record","name":"R","fields":[)"
           R"({"name":"a","type":"boolean"},{"name":"b","type":"boolean"}]})",
           std::string("\x01\x00", 2)},
          // A string field, then a union field on its int branch.
          {R"({"type":"record","name":"R","fields":[)"
           R"({"name":"a","type":"string"},)"
           R"({"name":"b","type":["null","int"]}]})",
           Varint(2) + "hi" + Varint(1) + Varint(3)},

          {R"({"type":"int","logicalType":"date"})", Varint(19000)},
          {R"({"type":"long","logicalType":"timestamp-millis"})",
           Varint(1700000000000LL)},
          {R"({"type":"string","logicalType":"uuid"})",
           Varint(36) + "6ba7b810-9dad-11d1-80b4-00c04fd430c8"},
          {R"({"type":"bytes","logicalType":"decimal",)"
           R"("precision":9,"scale":2})",
           Varint(2) + std::string("\x01\x02", 2)},
      };
  return *encodings;
}

fuzztest::Domain<std::string> AnySchemaText() {
  return fuzztest::OneOf(fuzztest::ElementOf<std::string>(SchemaSeeds()),
                         fuzztest::Arbitrary<std::string>().WithMaxSize(96));
}

// avro-cpp decides whitespace with isspace() (JsonIO.cc:42), which accepts
// vertical tab and form feed. JSON allows only tab, newline, carriage return
// and space, so those two bytes are avro-cpp's alone: it accepts them before,
// after and inside a schema, and the bridge rejects all three positions. Given
// its own tag so the table entry that mutes it cannot also mute an unrelated
// parser disagreement.
bool HoldsNonJsonWhitespace(absl::string_view text) {
  for (const char c : text) {
    if (c == '\v' || c == '\f') return true;
  }
  return false;
}

void ParsersAgreeOnSchemaAcceptance(const std::string& text) {
  const auto bridge = AvroSchema::Parse(text);
  const absl::Status cpp = ParseWithAvrocpp(text, nullptr);
  if (bridge.ok() == cpp.ok()) return;

  const std::string bridge_verdict =
      bridge.ok() ? std::string("accepted")
                  : "rejected: " + std::string(bridge.status().message());
  const std::string cpp_verdict =
      cpp.ok() ? std::string("accepted")
               : "rejected: " + std::string(cpp.message());

  absl::string_view tag = "schema-acceptance";
  if (!bridge.ok() && cpp.ok() && HoldsNonJsonWhitespace(text)) {
    tag = "json-whitespace-leniency";
  } else if (!bridge.ok() && cpp.ok() && ParsesAsSchemaPrefix(text)) {
    tag = "schema-trailing-bytes";
  }
  ReportDivergence(std::string(tag),
                   "the two parsers disagree on whether this schema is legal"
                   "\n  text:    " +
                       text + "\n  bridge:  " + bridge_verdict +
                       "\n  avrocpp: " + cpp_verdict);
}
FUZZ_TEST(AvroBytes, ParsersAgreeOnSchemaAcceptance)
    .WithDomains(AnySchemaText());

void DecodersAgreeOnAcceptance(const std::string& schema_text,
                               const std::string& bytes) {
  if (DeclaresLengthBeyondLimit(bytes, kMaxDeclaredLengthBytes)) return;

  auto bridge_schema = AvroSchema::Parse(schema_text);
  ::avro::ValidSchema cpp_schema;
  const absl::Status parsed = ParseWithAvrocpp(schema_text, &cpp_schema);
  if (!bridge_schema.ok() || !parsed.ok()) return;

  const auto bridge = security::avro::DecodeDatum(*bridge_schema, bytes);
  ::avro::GenericDatum datum;
  const absl::Status cpp = DecodeWithAvrocpp(cpp_schema, bytes, &datum);
  if (bridge.ok() == cpp.ok()) return;

  const std::string bridge_error =
      bridge.ok() ? std::string() : std::string(bridge.status().message());
  std::string tag = bridge.ok() ? "bridge-lenient" : "avrocpp-lenient";
  if (!bridge.ok()) {
    if (bridge_error.find("Unable to allocate") != std::string::npos) {
      // avro-cpp has no ceiling, so whether it refuses the same input depends
      // on available memory rather than on the input.
      tag = "alloc-ceiling";
    } else if (bridge_error.find("trailing bytes") != std::string::npos) {
      tag = "trailing-bytes";
    } else if (bridge_error.find("Rust panic caught") != std::string::npos) {
      tag = "rust-panic";
    }
  }
  const bool generic = tag == "bridge-lenient" || tag == "avrocpp-lenient";
  if (generic && IsArraySchema(schema_text)) tag = "array-block-framing";
  ReportDivergence(
      tag,
      "the two decoders disagree on whether these bytes are decodable"
      "\n  schema:  " +
          schema_text + "\n  bytes:   " + absl::BytesToHexString(bytes) + " (" +
          std::to_string(bytes.size()) + ")\n  bridge:  " +
          (bridge.ok() ? std::string("accepted")
                       : "rejected: " + bridge_error) +
          "\n  avrocpp: " +
          (cpp.ok() ? std::string("accepted")
                    : "rejected: " + std::string(cpp.message())));
}
FUZZ_TEST(AvroBytes, DecodersAgreeOnAcceptance)
    .WithDomains(fuzztest::ElementOf<std::string>(DecodableSchemas()),
                 fuzztest::Arbitrary<std::string>().WithMaxSize(64));

// Acceptance alone says nothing about what was decoded, so this property checks
// the values too: when both engines accept the same bytes, each re-encodes what
// it decoded with its own encoder and the two encodings are compared.
//
// What that buys, and what it costs. Comparing encodings covers the whole value
// including nesting without a per-type comparator, but it cannot say which half
// of the circle diverged: a mismatch means the decoders disagreed, or the
// encoders did, or both. Attributing one needs the value walked field by field.
// A mismatch here is therefore a starting point for triage, not a decode bug on
// its own.

void ReencodingAgreesWhenBothDecode(const std::string& schema_text,
                                    const std::string& bytes) {
  if (DeclaresLengthBeyondLimit(bytes, kMaxDeclaredLengthBytes)) return;

  auto bridge_schema = AvroSchema::Parse(schema_text);
  ::avro::ValidSchema cpp_schema;
  const absl::Status parsed = ParseWithAvrocpp(schema_text, &cpp_schema);
  if (!bridge_schema.ok() || !parsed.ok()) return;

  const auto bridge_value = security::avro::DecodeDatum(*bridge_schema, bytes);
  ::avro::GenericDatum cpp_value;
  const absl::Status cpp_decoded =
      DecodeWithAvrocpp(cpp_schema, bytes, &cpp_value);
  // Disagreement on acceptance is DecodersAgreeOnAcceptance's business.
  if (!bridge_value.ok() || !cpp_decoded.ok()) return;

  const auto bridge_reencoded =
      security::avro::EncodeDatum(*bridge_schema, *bridge_value);
  std::string cpp_reencoded;
  const absl::Status cpp_encoded =
      EncodeWithAvrocpp(cpp_schema, cpp_value, &cpp_reencoded);

  if (!bridge_reencoded.ok() || !cpp_encoded.ok()) {
    // One engine decoded a value its own encoder will not accept back.
    ReportDivergence(
        "reencode-failed",
        "both decoded these bytes but re-encoding failed"
        "\n  schema:  " +
            schema_text + "\n  bytes:   " + absl::BytesToHexString(bytes) +
            "\n  bridge:  " +
            (bridge_reencoded.ok()
                 ? std::string("re-encoded")
                 : "failed: " +
                       std::string(bridge_reencoded.status().message())) +
            "\n  avrocpp: " +
            (cpp_encoded.ok()
                 ? std::string("re-encoded")
                 : "failed: " + std::string(cpp_encoded.message())));
    return;
  }

  if (*bridge_reencoded == cpp_reencoded) return;

  ReportDivergence(
      IsArraySchema(schema_text) ? "array-block-framing" : "reencode-differs",
      "both decoded these bytes but re-encoded them differently"
      "\n  schema:  " +
          schema_text + "\n  input:   " + absl::BytesToHexString(bytes) +
          "\n  bridge:  " + absl::BytesToHexString(*bridge_reencoded) +
          "\n  avrocpp: " + absl::BytesToHexString(cpp_reencoded));
}
FUZZ_TEST(AvroBytes, ReencodingAgreesWhenBothDecode)
    .WithDomains(fuzztest::ElementOf<std::string>(RoundTripSchemas()),
                 fuzztest::Arbitrary<std::string>().WithMaxSize(64))
    .WithSeeds(ValidEncodings());

// ---------------------------------------------------------------------------
// One test per divergence in kKnownDivergences, so each is visible on its own
// and fails the moment the behaviour changes. Each spells out what both engines
// do with the same input.
// ---------------------------------------------------------------------------

void ExpectSchemaAcceptance(const std::string& schema, bool bridge_accepts,
                            bool avrocpp_accepts) {
  EXPECT_EQ(AvroSchema::Parse(schema).ok(), bridge_accepts)
      << "the bridge on " << schema;
  EXPECT_EQ(ParseWithAvrocpp(schema, nullptr).ok(), avrocpp_accepts)
      << "avro-cpp on " << schema;
}

void ExpectDecodeAcceptance(const std::string& schema, const std::string& bytes,
                            bool bridge_accepts, bool avrocpp_accepts) {
  auto bridge_schema = AvroSchema::Parse(schema);
  ASSERT_TRUE(bridge_schema.ok()) << bridge_schema.status();
  ::avro::ValidSchema cpp_schema;
  ASSERT_TRUE(ParseWithAvrocpp(schema, &cpp_schema).ok()) << schema;

  const auto bridge = security::avro::DecodeDatum(*bridge_schema, bytes);
  EXPECT_EQ(bridge.ok(), bridge_accepts)
      << "the bridge on " << absl::BytesToHexString(bytes) << ": "
      << (bridge.ok() ? "accepted" : std::string(bridge.status().message()));

  ::avro::GenericDatum datum;
  const absl::Status cpp = DecodeWithAvrocpp(cpp_schema, bytes, &datum);
  EXPECT_EQ(cpp.ok(), avrocpp_accepts)
      << "avro-cpp on " << absl::BytesToHexString(bytes) << ": "
      << (cpp.ok() ? "accepted" : std::string(cpp.message()));
}

// Drives the same circle as ReencodingAgreesWhenBothDecode, but asserts every
// step instead of returning early, so the inputs below are known to reach the
// comparison. The property alone could pass indefinitely while never getting
// past its decode guard, and a passing test that compares nothing is worse than
// no test.
void ExpectReencodingAgrees(const std::string& schema,
                            const std::string& bytes) {
  auto bridge_schema = AvroSchema::Parse(schema);
  ASSERT_TRUE(bridge_schema.ok()) << bridge_schema.status();
  ::avro::ValidSchema cpp_schema;
  ASSERT_TRUE(ParseWithAvrocpp(schema, &cpp_schema).ok()) << schema;

  const auto bridge_value = security::avro::DecodeDatum(*bridge_schema, bytes);
  ASSERT_TRUE(bridge_value.ok())
      << "the bridge on " << absl::BytesToHexString(bytes) << ": "
      << bridge_value.status().message();
  ::avro::GenericDatum cpp_value;
  const absl::Status cpp_decoded =
      DecodeWithAvrocpp(cpp_schema, bytes, &cpp_value);
  ASSERT_TRUE(cpp_decoded.ok())
      << "avro-cpp on " << absl::BytesToHexString(bytes) << ": "
      << cpp_decoded.message();

  const auto bridge_reencoded =
      security::avro::EncodeDatum(*bridge_schema, *bridge_value);
  ASSERT_TRUE(bridge_reencoded.ok()) << bridge_reencoded.status();
  std::string cpp_reencoded;
  const absl::Status cpp_encoded =
      EncodeWithAvrocpp(cpp_schema, cpp_value, &cpp_reencoded);
  ASSERT_TRUE(cpp_encoded.ok()) << cpp_encoded.message();

  // Compared as hex so a mismatch prints legibly.
  EXPECT_EQ(absl::BytesToHexString(*bridge_reencoded),
            absl::BytesToHexString(cpp_reencoded))
      << "schema " << schema << " on input " << absl::BytesToHexString(bytes);
}

TEST(AvroBytes, ReencodingAgreesOnValidEncodings) {
  ASSERT_FALSE(ValidEncodings().empty());
  for (const auto& [schema, bytes] : ValidEncodings()) {
    ExpectReencodingAgrees(schema, bytes);
  }
}

// Why maps sit outside the round-trip property. Feeding these bytes through the
// circle was measured over 15 runs: the two re-encodings differed in 6 of them
// and matched in the other 9, because the bridge writes entries in its HashMap
// iteration order and Rust seeds that per process, while avro-cpp writes them
// in the order they arrived on the wire. Avro fixes no map entry order, so
// neither engine is wrong and a byte comparison would fail intermittently for
// no reason.
//
// What is stable is the content, which is what this test pins, along with the
// exclusion itself.
TEST(AvroBytes, MapsAreExcludedBecauseReencodedEntryOrderIsUnstable) {
  const std::string schema = R"({"type":"map","values":"int"})";
  // Deliberately not in sorted key order, so any reordering is visible.
  const std::string bytes = Varint(2) + Varint(1) + "b" + Varint(20) +
                            Varint(1) + "a" + Varint(10) + Varint(0);

  auto bridge_schema = AvroSchema::Parse(schema);
  ASSERT_TRUE(bridge_schema.ok()) << bridge_schema.status();
  const auto value = security::avro::DecodeDatum(*bridge_schema, bytes);
  ASSERT_TRUE(value.ok()) << value.status();

  const auto keys = value->GetMapKeys();
  ASSERT_TRUE(keys.ok()) << keys.status();
  EXPECT_EQ(*keys, (std::vector<std::string>{"a", "b"}));

  const auto first = value->GetMapValue("a");
  ASSERT_TRUE(first.ok()) << first.status();
  EXPECT_EQ(first->GetInt().value_or(0), 10);
  const auto second = value->GetMapValue("b");
  ASSERT_TRUE(second.ok()) << second.status();
  EXPECT_EQ(second->GetInt().value_or(0), 20);

  // Checked through the parser rather than through MentionsMap, so this is not
  // the filter grading its own work: a map schema written with a space after
  // the colon would slip past the text match and has to be caught here. A map
  // nested inside a record would still get through, which today no seed schema
  // has; the cost if one is added is a noisy report, not a hidden divergence.
  for (const std::string& round_trip_schema : RoundTripSchemas()) {
    auto parsed = AvroSchema::Parse(round_trip_schema);
    ASSERT_TRUE(parsed.ok()) << round_trip_schema;
    EXPECT_FALSE(parsed->IsMap()) << round_trip_schema;
  }
  EXPECT_EQ(RoundTripSchemas().size() + 2, DecodableSchemas().size())
      << "the two map schemas are the only ones the round trip skips";
}

// CLOSED. Was schema-acceptance / "bad node of type union". The empty-union
// patch rejects it at parse, in UnionSchema::new, where the crate used to log an
// error and carry on. No branch index is in range for an empty union, so nothing
// encodes into one and no bytes decode under one; the bridge used to accept such
// a schema and render it straight back, so it round-tripped something avro-cpp
// cannot read.
TEST(AvroBytes, EmptyUnionIsRejectedByBothEngines) {
  for (const char* text : {
           R"([])",
           R"([[]])",
           R"({"type":"record","name":"R","fields":[{"name":"a","type":[]}]})",
           R"({"type":"array","items":[]})",
           R"({"type":"map","values":[]})",
       }) {
    ExpectSchemaAcceptance(text, false, false);
  }

  // A one-branch union stays legal on both sides: index 0 is in range, so it
  // has a valid encoding. This is what keeps the fix from over-reaching.
  ExpectSchemaAcceptance(R"(["int"])", true, true);
  ExpectReencodingAgrees(R"(["int"])", Varint(0) + Varint(42));
}

// CLOSED. Was schema-acceptance / "bad node of type enum", the same defect as
// the empty union above on a different construct: no symbol index is in range,
// so it has no valid encoding. The empty-enum patch rejects it in parse_enum.
//
// The check is on the parse path only. EnumSchema has public fields and a
// builder, unlike UnionSchema whose fields are crate-private, so a Rust caller
// can still hand-build one with no symbols. Untrusted input arrives by parsing,
// which is what this covers.
TEST(AvroBytes, EmptyEnumIsRejectedByBothEngines) {
  for (const char* text : {
           R"({"type":"enum","name":"E","symbols":[]})",
           R"({"type":"enum","name":"E","namespace":"ns","symbols":[]})",
           R"({"type":"record","name":"R","fields":[{"name":"a","type":)"
           R"({"type":"enum","name":"E","symbols":[]}}]})",
           R"({"type":"array","items":)"
           R"({"type":"enum","name":"E","symbols":[]}})",
       }) {
    ExpectSchemaAcceptance(text, false, false);
  }

  // One symbol is enough on both sides: index 0 is in range.
  const std::string one = R"({"type":"enum","name":"E","symbols":["A"]})";
  ExpectSchemaAcceptance(one, true, true);
  ExpectReencodingAgrees(one, Varint(0));
}

// schema-acceptance / "Invalid namespace"
TEST(AvroBytes, NamespaceWithAnEmptyComponentIsAcceptedByAvrocppOnly) {
  // The spec requires each namespace component to be a name, so avro-cpp is
  // the lenient one here.
  ExpectSchemaAcceptance(
      R"({"type":"fixed","name":"F","namespace":"ns..bad","size":16})", false,
      true);
}

// CLOSED. Was bridge-lenient / "EOF reached", the most serious of the eleven:
// the bridge decoded a truncated buffer into data that was never on the wire.
// The strict-eof patch closes it. Three arms of apache-avro's decoder treated
// end of input as a value rather than an error, and all three now propagate it.
//
// The truncated-string row is the one the old pinning test could not reach. An
// empty buffer under "string" already failed, because the length prefix is
// missing, so nothing exercised a length prefix with too few bytes behind it.
// That was the third fabrication site and it is closed by the same patch.
TEST(AvroBytes, TruncatedInputIsRejectedByBothEngines) {
  const std::string record =
      R"({"type":"record","name":"R","fields":[)"
      R"({"name":"a","type":"boolean"},{"name":"b","type":"boolean"}]})";
  ExpectDecodeAcceptance(record, std::string(), false, false);

  // Type-dependent before the fix, which is what made it easy to miss. Every
  // row below used to differ; now every row agrees.
  ExpectDecodeAcceptance(R"("boolean")", std::string(), false, false);
  ExpectDecodeAcceptance(R"(["int"])", std::string(), false, false);
  // Branch 0 is null here, so the fabricated value was type-correct by luck.
  // It was still a value read from no input.
  ExpectDecodeAcceptance(R"(["null","int"])", std::string(), false, false);
  // A length prefix of 2 with one byte behind it.
  const std::string truncated_payload = Varint(2) + "a";
  ExpectDecodeAcceptance(R"("string")", truncated_payload, false, false);
  ExpectDecodeAcceptance(R"("bytes")", truncated_payload, false, false);

  // Unchanged, and the reason the fix could not be "reject an empty buffer":
  // a null datum really does occupy zero bytes, so both engines read one and
  // both re-encode it to nothing.
  ExpectDecodeAcceptance(R"("null")", std::string(), true, true);
  ExpectReencodingAgrees(R"("null")", std::string());

  // These two always agreed and still do, so the patch did not reach further
  // than the fabrication.
  ExpectDecodeAcceptance(R"("int")", std::string(), false, false);
  ExpectDecodeAcceptance(R"("string")", std::string(), false, false);
}

// trailing-bytes / "trailing bytes"
TEST(AvroBytes, TrailingBytesAreAcceptedByAvrocppOnly) {
  // One int, then a byte that is not part of it.
  ExpectDecodeAcceptance(R"("int")", Varint(1) + std::string(1, '\x7f'), false,
                         true);
}

// EXPERIMENT. Was avrocpp-lenient / "Invalid utf-8", with the bridge rejecting.
// The non-UTF-8 patch closes it: the bridge accepts and the payload survives as
// bytes, so both engines re-encode to what they were given.
TEST(AvroBytes, NonUtf8StringRoundTripsThroughBothEngines) {
  // Length 1, then a lone UTF-8 continuation byte.
  const std::string bytes = Varint(1) + std::string(1, '\x80');
  ExpectDecodeAcceptance(R"("string")", bytes, true, true);
  ExpectDecodeAcceptance(R"("bytes")", bytes, true, true);

  auto schema = AvroSchema::Parse(R"("string")");
  ASSERT_TRUE(schema.ok()) << schema.status();
  const auto value = security::avro::DecodeDatum(*schema, bytes);
  ASSERT_TRUE(value.ok()) << value.status();
  EXPECT_TRUE(value->IsBytes()) << "type is " << value->TypeName();
  EXPECT_EQ(value->GetBytes().value_or(""), std::string(1, '\x80'));

  // Acceptance says nothing about what was decoded, so drive the whole circle.
  ExpectReencodingAgrees(R"("string")", bytes);
  // Split literals: "\xffb" would lex as one out-of-range hex escape.
  ExpectReencodingAgrees(R"("string")",
                         Varint(4) + std::string("a\xff" "b\x80", 4));
  // A valid UTF-8 string still decodes as a string and is unaffected.
  ExpectReencodingAgrees(R"("string")", Varint(3) + "abc");
}

// EXPERIMENT. Was avrocpp-lenient / "to UUID", with the bridge rejecting text
// that is not a uuid. The uuid-as-string patch closes it, and closes the four
// shapes around it that the acceptance property could never have seen because
// both engines accepted them and only the decoded value differed.
TEST(AvroBytes, UuidIsReadAsAnOrdinaryStringByBothEngines) {
  const std::string uuid_schema = R"({"type":"string","logicalType":"uuid"})";

  // Text that is not a uuid at all: both read it now.
  const std::string text = "not-a-uuid";
  ExpectDecodeAcceptance(uuid_schema,
                         Varint(static_cast<int64_t>(text.size())) + text, true,
                         true);

  // Every spelling below parses as a uuid, so the parsing path rewrote it to
  // canonical hyphenated lowercase and the bytes changed. Read as a string they
  // survive, which is what these assert.
  for (const std::string& body : {
           std::string("6ba7b810-9dad-11d1-80b4-00c04fd430c8"),  // canonical
           std::string("6BA7B810-9DAD-11D1-80B4-00C04FD430C8"),  // upper case
           std::string("urn:uuid:6ba7b810-9dad-11d1-80b4-00c04fd430c8"),
           std::string("{6ba7b810-9dad-11d1-80b4-00c04fd430c8}"),
           std::string("6ba7b8109dad11d180b400c04fd430c8"),  // no hyphens
           std::string("not-a-uuid"),
           std::string(""),
           // Exactly 16 bytes, which the parsing path took as a raw uuid and
           // returned as 36 characters of hex.
           std::string("  St9exception  "),
       }) {
    ExpectReencodingAgrees(uuid_schema,
                           Varint(static_cast<int64_t>(body.size())) + body);
  }

  // Non-UTF-8 under a uuid schema needs both patches: the uuid one to reach the
  // string path at all, the other to tolerate the bytes once there.
  ExpectReencodingAgrees(uuid_schema,
                         Varint(3) + std::string("\xff\xfe\xfd", 3));
}

// alloc-ceiling / "Unable to allocate"
TEST(AvroBytes, OversizedLengthStopsAtTheBridgeCeilingOnly) {
  // A bytes field declaring 256 MiB with nothing behind it. The bridge refuses
  // at its ceiling by policy; avro-cpp has no ceiling and only fails because
  // the data is not there, so this input is not comparable in either
  // direction and the fuzz property reports it under its own tag.
  const std::string bytes = Varint(256 << 20);
  ExpectDecodeAcceptance(R"("bytes")", bytes, false, false);

  auto bridge_schema = AvroSchema::Parse(R"("bytes")");
  ASSERT_TRUE(bridge_schema.ok());
  const auto bridge = security::avro::DecodeDatum(*bridge_schema, bytes);
  ASSERT_FALSE(bridge.ok());
  EXPECT_NE(std::string(bridge.status().message()).find("Unable to allocate"),
            std::string::npos)
      << bridge.status().message();
}

// Not an acceptance divergence. The bridge's allocation ceiling compares the
// declared collection *count* against a limit expressed in *bytes*, so a count
// just under the limit passes and the map it then reserves costs about 166
// bytes per entry.
//
// What happens next depends on the host rather than the input: where the
// reservation cannot be satisfied the process aborts, because Rust's
// handle_alloc_error aborts rather than returning an error, and on this host
// overcommit satisfies it and the decode fails cleanly on the missing data.
// The measured abort message was "memory allocation of 5435817992 bytes
// failed". Only the ceiling arithmetic is asserted here, since that is the part
// that does not vary.
//
// DeclaresLengthBeyondLimit keeps such inputs out of the fuzz property, which
// would otherwise abort mid-run on a constrained host.
TEST(AvroBytes, AllocationCeilingChecksCountAgainstAByteLimit) {
  const std::string schema = R"({"type":"map","values":"int"})";
  auto bridge_schema = AvroSchema::Parse(schema);
  ASSERT_TRUE(bridge_schema.ok()) << bridge_schema.status();

  // Above the 64 MiB ceiling: refused, and the number in the message is the
  // entry count rather than the bytes the map would occupy.
  const auto refused =
      security::avro::DecodeDatum(*bridge_schema, Varint(1LL << 30));
  ASSERT_FALSE(refused.ok());
  EXPECT_NE(std::string(refused.status().message())
                .find("Unable to allocate 1073741824 bytes"),
            std::string::npos)
      << refused.status().message();

  // Just under it: the ceiling passes it through, so the reservation that
  // follows is roughly 166 times the number that was checked.
  const auto allowed =
      security::avro::DecodeDatum(*bridge_schema, Varint(32767935));
  ASSERT_FALSE(allowed.ok());
  EXPECT_EQ(std::string(allowed.status().message())
                .find("Unable to allocate"),
            std::string::npos)
      << "the ceiling now covers this count, so the gap is closed: "
      << allowed.status().message();
}

// reencode-failed / "decimal sign extension 0"
//
// Found by ReencodingAgreesWhenBothDecode within five minutes of fuzzing, and
// the first finding the acceptance properties could not have reached: both
// engines accept the input, so they never disagree on acceptance.
//
// A single 0x00 byte under a decimal schema is a length prefix of zero, so the
// unscaled value is an empty byte array. Avro's spec describes that value as a
// two's-complement big-endian integer, which needs at least one byte, so the
// input is arguably malformed and rejecting it would be reasonable. Neither
// decoder does.
//
// What the bridge does instead is worse than either accepting or rejecting: it
// reports success and hands back a value that says it is a decimal but whose
// bytes cannot be read and which its own encoder will not take back, both
// failing with the same message. A caller that decodes this input has no way to
// use or forward the result. avro-cpp decodes it and re-encodes it to the byte
// it came from.
TEST(AvroBytes, EmptyDecimalDecodesToAValueTheBridgeCannotReadOrReencode) {
  const std::string schema =
      R"({"type":"bytes","logicalType":"decimal","precision":9,"scale":2})";
  const std::string bytes = Varint(0);  // a zero-length unscaled value

  auto bridge_schema = AvroSchema::Parse(schema);
  ASSERT_TRUE(bridge_schema.ok()) << bridge_schema.status();
  ::avro::ValidSchema cpp_schema;
  ASSERT_TRUE(ParseWithAvrocpp(schema, &cpp_schema).ok()) << schema;

  const auto bridge_value = security::avro::DecodeDatum(*bridge_schema, bytes);
  ASSERT_TRUE(bridge_value.ok())
      << "the bridge rejected the input outright, which would be a change: "
      << bridge_value.status().message();
  EXPECT_TRUE(bridge_value->IsDecimal());

  // The value claims to be a decimal but will not yield its bytes.
  const auto decimal_bytes = bridge_value->GetDecimalBytes();
  EXPECT_FALSE(decimal_bytes.ok());
  EXPECT_NE(std::string(decimal_bytes.status().message())
                .find("decimal sign extension 0"),
            std::string::npos)
      << decimal_bytes.status().message();

  // And the bridge's own encoder refuses what its decoder produced.
  const auto reencoded =
      security::avro::EncodeDatum(*bridge_schema, *bridge_value);
  EXPECT_FALSE(reencoded.ok());
  EXPECT_NE(std::string(reencoded.status().message())
                .find("decimal sign extension 0"),
            std::string::npos)
      << reencoded.status().message();

  // avro-cpp completes the circle back to the input byte.
  ::avro::GenericDatum cpp_value;
  ASSERT_TRUE(DecodeWithAvrocpp(cpp_schema, bytes, &cpp_value).ok());
  std::string cpp_reencoded;
  ASSERT_TRUE(EncodeWithAvrocpp(cpp_schema, cpp_value, &cpp_reencoded).ok());
  EXPECT_EQ(absl::BytesToHexString(cpp_reencoded),
            absl::BytesToHexString(bytes));
}

// schema-trailing-bytes
//
// avrocpp stops once it has a complete JSON value and never looks at what
// follows, so a schema document with anything after it still parses. The bridge
// refuses it, in three different messages depending on where the trailing bytes
// fail first: bad JSON, invalid UTF-8, or a UTF-8 sequence cut short. One root
// cause, so one entry, classified by ParsesAsSchemaPrefix rather than by which
// message came back.
//
// More than parser strictness: a schema is a cache key and a fingerprint input.
// Two documents differing only in trailing bytes are the same schema to avrocpp
// and not a schema at all to the bridge, so a producer on one side can write
// something the other will not load.
TEST(AvroBytes, TrailingBytesAfterASchemaAreAcceptedByAvrocppOnly) {
  // Trailing text that is valid UTF-8: the JSON parser is what refuses it.
  for (const std::string& suffix : {"\"", "!", " x", "\n\n]"}) {
    ExpectSchemaAcceptance(R"("string")" + suffix, false, true);
  }
  // Trailing bytes that are not valid UTF-8, and a UTF-8 sequence cut short.
  // Both are checked before the text reaches the JSON parser.
  ExpectSchemaAcceptance(R"("int")" + std::string("f_\xc3\x28y", 5), false,
                         true);
  ExpectSchemaAcceptance(R"("double")" + std::string("l5\xe2\x82", 4), false,
                         true);

  // All three are one shape, which is what the classifier keys on.
  EXPECT_TRUE(ParsesAsSchemaPrefix(R"("string")"
                                   "!"));
  EXPECT_TRUE(ParsesAsSchemaPrefix(R"("int")" + std::string("f_\xc3\x28y", 5)));
  // A schema that is merely truncated has no prefix that parses, so it stays a
  // plain schema-acceptance divergence rather than being absorbed here.
  EXPECT_FALSE(ParsesAsSchemaPrefix(R"({"type":"reco)"));

  // Trailing whitespace alone is fine on both sides, so the divergence is the
  // trailing content and not merely a length mismatch.
  ExpectSchemaAcceptance(R"("string")"
                         "  \n",
                         true, true);
}

// avrocpp-lenient / "Invalid utf-8 string"
//
// The non-UTF-8 patch relaxes `string` but deliberately leaves map keys strict,
// because apache-avro keys a map with a Rust `String` and a key that is not
// UTF-8 has nowhere to live. avrocpp keys with a byte-oriented std::string and
// takes it. So the setting closes the `string` case and not this one, which is
// a limit of the value model rather than a decision that could be flipped.
//
// This is now the only path left that produces this message: the plain-string
// case is closed, and the uuid one went with the uuid-as-string patch.
TEST(AvroBytes, NonUtf8MapKeyIsAcceptedByAvrocppOnly) {
  // One entry: a one-byte key that is a lone UTF-8 continuation byte, the int
  // 1, then the terminating zero-length block.
  const std::string bytes = Varint(1) + Varint(1) + std::string(1, '\x80') +
                            Varint(1) + Varint(0);
  ExpectDecodeAcceptance(R"({"type":"map","values":"int"})", bytes, false,
                         true);

  // The same key bytes as a `string` value are fine on both sides, which is
  // what separates the key restriction from the string one.
  ExpectDecodeAcceptance(R"("string")", Varint(1) + std::string(1, '\x80'),
                         true, true);
}

// array-block-framing
//
// One entry and one test for what were five, because they are five spellings of
// one root cause: Avro does not define recovery from a malformed array block
// header, so each engine invented its own and they do not match. Recording a
// message per spelling was open-ended, since a header can be malformed in as
// many ways as a varint can be written.
//
// Every row below was found by the fuzzer and reproduces on this host. What
// they share is that the header, not the items, decides the outcome.
//
// The last row is the one worth fixing first. Both engines accept it, so no
// acceptance check could ever see it, and avrocpp returns nine items it never
// read, filled with zeros, with nothing to tell a caller that most of the value
// was invented.
TEST(AvroBytes, ArrayBlockHeaderRecoveryDiverges) {
  const std::string ints = R"({"type":"array","items":"int"})";
  const std::string strings = R"({"type":"array","items":"string"})";

  // A 30-item block, then a second header with nothing behind it. avrocpp hands
  // back 29 items, one fewer than declared, with no error. The 29-versus-30 is
  // not explained and is recorded as measured; shorter arrays of the same shape
  // are rejected by both.
  const std::string truncated = Varint(-30) + Varint(0) +
                                std::string(30, '\0') + Varint(-1) + Varint(0);
  ExpectDecodeAcceptance(ints, truncated, false, true);
  {
    ::avro::ValidSchema cpp_schema;
    ASSERT_TRUE(ParseWithAvrocpp(ints, &cpp_schema).ok());
    ::avro::GenericDatum datum;
    ASSERT_TRUE(DecodeWithAvrocpp(cpp_schema, truncated, &datum).ok());
    ASSERT_EQ(datum.type(), ::avro::AVRO_ARRAY);
    EXPECT_EQ(datum.value<::avro::GenericArray>().value().size(), 29u);
  }

  // A count avrocpp sizes a vector from, dying of std::length_error before it
  // reads anything, where the bridge reads 58 items. The message is libstdc++'s
  // wording, so this row is tied to the standard library as well as to avrocpp.
  const std::string oversized = FromHex(
      "0e7479706539726465656c6f6769744e346176726f374465636f6465727379"
      "6d626f6c7372785821abd33a1f673b757863657074696f6e6e472062797465"
      "6300");
  ExpectDecodeAcceptance(ints, oversized, true, false);

  // A negative count promises items and a byte size; the size is negative too.
  // The bridge will not turn that into a length, avrocpp reads on.
  ExpectDecodeAcceptance(
      strings, FromHex("0202020202020202020202020202020300e3c901ff020202"),
      false, true);

  // A header whose varint overflows the long it is read into. Not overflow in
  // general: the same varint where an item is expected overflows on both sides,
  // which the contrast below pins, so it is the header position that diverges.
  ExpectDecodeAcceptance(
      ints, FromHex("07070707170707000707646f637479706583838383838383838383"),
      false, true);
  ExpectDecodeAcceptance(R"("int")",
                         std::string(6, '\x83') + std::string(1, '\x01'), false,
                         false);

  // Both accept and only the values differ. A 10-item block, then a header
  // declaring -3 items with a byte size of -3, which is not a size.
  const std::string ambiguous =
      Varint(10) + Varint(10) + Varint(10) + Varint(10) + Varint(-134620) +
      Varint(-41) + Varint(1286) + Varint(10) + Varint(10) + Varint(-3) +
      Varint(-3) + Varint(-3) + Varint(-3) + Varint(-3) + Varint(10) +
      Varint(10) + Varint(0);
  ASSERT_EQ(ambiguous.size(), 20u) << absl::BytesToHexString(ambiguous);

  auto schema = AvroSchema::Parse(ints);
  ASSERT_TRUE(schema.ok()) << schema.status();
  ::avro::ValidSchema cpp_schema;
  ASSERT_TRUE(ParseWithAvrocpp(ints, &cpp_schema).ok());

  const auto bridge_value = security::avro::DecodeDatum(*schema, ambiguous);
  ASSERT_TRUE(bridge_value.ok()) << bridge_value.status();
  EXPECT_EQ(bridge_value->GetArrayLen().value_or(0), 13u);

  ::avro::GenericDatum cpp_value;
  ASSERT_TRUE(DecodeWithAvrocpp(cpp_schema, ambiguous, &cpp_value).ok());
  const auto& cpp_items = cpp_value.value<::avro::GenericArray>().value();
  EXPECT_EQ(cpp_items.size(), 11u);

  EXPECT_EQ(bridge_value->GetArrayItem(0)->GetInt().value_or(0), 10);
  EXPECT_EQ(cpp_items[0].value<int32_t>(), 10);
  EXPECT_EQ(bridge_value->GetArrayItem(3)->GetInt().value_or(0), -134620);
  EXPECT_EQ(cpp_items[3].value<int32_t>(), 0);
  size_t cpp_zeros = 0;
  for (const auto& item : cpp_items) {
    if (item.value<int32_t>() == 0) ++cpp_zeros;
  }
  EXPECT_EQ(cpp_zeros, 9u) << "avro-cpp invented nine items";
}

// NEW FINDING, found by ParsersAgreeOnSchemaAcceptance in 23 seconds.
//
// avro-cpp calls isspace() to skip whitespace (JsonIO.cc:42), so it accepts
// vertical tab (0x0B) and form feed (0x0C) wherever JSON permits whitespace.
// RFC 8259 permits exactly four bytes there -- tab, newline, carriage return,
// space -- and serde_json, under the bridge, enforces that. Every other byte
// from 0x00 to 0x20 gets the same verdict from both.
//
// Direction is avro-cpp-lenient, so nothing is mis-decoded: a schema the bridge
// accepts, avro-cpp also accepts. It matters the other way round, when a
// pipeline that fed avro-cpp a pretty-printed schema containing a form feed
// starts failing to parse after moving to the bridge.
TEST(AvroBytes, VerticalTabAndFormFeedAreWhitespaceOnlyToAvrocpp) {
  for (const char byte : {'\v', '\f'}) {
    const std::string before = std::string(1, byte) + R"("int")";
    const std::string after = R"("int")" + std::string(1, byte);
    const std::string inside =
        R"({"type":)" + std::string(1, byte) + R"("int"})";
    for (const std::string& text : {before, after, inside}) {
      EXPECT_TRUE(ParseWithAvrocpp(text, nullptr).ok())
          << "avro-cpp is expected to treat 0x" << std::hex
          << static_cast<int>(byte) << " as whitespace: " << text;
      EXPECT_FALSE(AvroSchema::Parse(text).ok())
          << "the bridge is expected to reject it; if it now accepts, "
             "serde_json widened its whitespace set and this finding is closed";
    }
  }

  // The four JSON whitespace bytes agree, which is what makes the two above a
  // finding rather than a general disagreement about leading bytes.
  for (const char byte : {'\t', '\n', '\r', ' '}) {
    const std::string text = std::string(1, byte) + R"("int")";
    EXPECT_TRUE(ParseWithAvrocpp(text, nullptr).ok()) << text;
    EXPECT_TRUE(AvroSchema::Parse(text).ok()) << text;
  }
}

TEST(AvroBytes, KnownDivergenceTableSizeIsPinned) {
  EXPECT_EQ(std::size(kKnownDivergences), 8u)
      << "adding an entry means adding a test named after it above; bump this "
         "count once you have";
}

}  // namespace
